// Auto-generated by wowhead-data-scraper on 2026-04-26. Review before committing.
import type { ClassGuide, Consumable } from './types';

const SHARED_CONSUMABLES: Consumable[] = [
  { type: 'healthPotion', name: 'Silvermoon Health Potion' },
  { type: 'weaponBuff', name: 'Thalassian Phoenix Oil' },
  { type: 'augmentRune', name: 'Void-Touched Augment Rune' },
];

const deathknightGuide: ClassGuide = {
  className: 'Death Knight',
  wowClass: 'deathknight',
  specs: [
    {
      specName: 'Blood',
      patch: '12.0.5',
      season: 'Midnight Season 1',
      lastUpdated: '2026-04-26',
      links: {
        cheatSheet: 'https://www.wowhead.com/guide/classes/death-knight/blood/cheat-sheet',
        talents: 'https://www.wowhead.com/guide/classes/death-knight/blood/talent-builds-pve-tank',
        rotation: 'https://www.wowhead.com/guide/classes/death-knight/blood/rotation-cooldowns-pve-tank',
        statPriority: 'https://www.wowhead.com/guide/classes/death-knight/blood/stat-priority-pve-tank',
        consumables: 'https://www.wowhead.com/guide/classes/death-knight/blood/enchants-gems-pve-tank',
        bisGear: 'https://www.wowhead.com/guide/classes/death-knight/blood/bis-gear',
        overview: 'https://www.wowhead.com/guide/classes/death-knight/blood/overview-pve-tank',
      },
      talentLoadouts: [
        { label: 'Raid', exportString: 'CoPAAAAAAAAAAAAAAAAAAAAAAwYWmZmxMmZmhZZmZmmZxYMmxAAAAAzMzMzMzMDzYMAgZmZGAAADMwMW0YZDklBsBYGmBAAmZghB' },
        { label: 'Mythic+', exportString: 'CoPAAAAAAAAAAAAAAAAAAAAAAwYWmZmxMmZmhZZmZmmZxYMmxAAAAAmxMzMzMDzYMAYMzMzAAAYgBmxiGLLgsMgNAzYmBAAmZghB' },
        { label: 'Open World', exportString: 'CoPAAAAAAAAAAAAAAAAAAAAAAwMzyMzMmxMzMMLzMz0MLGjxMGAAAAwMmZmZmZYGjBAjZmZGAAgxsNwAWCWGmADLAmhZAAMzAYYA' },
      ],
      statPriority: [
        { stat: 'Strength' },
        { stat: 'Haste' },
        { stat: 'Critical Strike' },
        { stat: 'Mastery' },
        { stat: 'Versatility' },
      ],
      consumables: [
        { type: 'flask', name: 'Flask of the Blood Knights / Flask of the Shattered Sun' },
        { type: 'potion', name: "Potion of Recklessness / Light's Potential" },
        { type: 'food', subType: 'personal', name: 'Harandar Celebration' },
        { type: 'food', subType: 'personal', name: 'Blooming Feast' },
        ...SHARED_CONSUMABLES,
      ],
      enchants: [
        { slot: 'Weapon', name: "Rune of Sanguination ( Deathbringer ST) Rune of the Fallen Crusader ( Deathbringer 5T+ AoE) Rune of Sanguination ( San'layn)" },
        { slot: 'Helm', name: 'Enchant Helm - Empowered Blessing of Speed' },
        { slot: 'Shoulders', name: "Enchant Shoulders - Akil'zon's Swiftness" },
        { slot: 'Chest', name: 'Enchant Chest - Mark of the Worldsoul' },
        { slot: 'Legs', name: "Forest Hunter's Armor Kit" },
        { slot: 'Feet', name: "Enchant Boots - Farstrider's Hunt" },
        { slot: 'Ring', name: "Enchant Ring - Nature's Fury", note: 'both rings' },
      ],
      gems: [
        { socketType: 'Eagle', name: 'Enchant Ring - Eyes of the Eagle' },
      ],
    },

    {
      specName: 'Frost',
      patch: '12.0.5',
      season: 'Midnight Season 1',
      lastUpdated: '2026-04-26',
      links: {
        cheatSheet: 'https://www.wowhead.com/guide/classes/death-knight/frost/cheat-sheet',
        talents: 'https://www.wowhead.com/guide/classes/death-knight/frost/talent-builds-pve-dps',
        rotation: 'https://www.wowhead.com/guide/classes/death-knight/frost/rotation-cooldowns-pve-dps',
        statPriority: 'https://www.wowhead.com/guide/classes/death-knight/frost/stat-priority-pve-dps',
        consumables: 'https://www.wowhead.com/guide/classes/death-knight/frost/enchants-gems-pve-dps',
        bisGear: 'https://www.wowhead.com/guide/classes/death-knight/frost/bis-gear',
        overview: 'https://www.wowhead.com/guide/classes/death-knight/frost/overview-pve-dps',
      },
      talentLoadouts: [
        { label: 'Raid', exportString: 'CsPAAAAAAAAAAAAAAAAAAAAAAMDwMjZMDY2mZmZmZZmZkZMmZYGGPgZGMzMzMDAAAAAAAAAjZbgBsAWGmQGLYmxMzAzAYYmBYmBD' },
        { label: 'Mythic+', exportString: 'CsPAAAAAAAAAAAAAAAAAAAAAAMAzMjZmZAz2MzMzMLmZkZMmZmZGYMzwMzMjZAAAAAAAAAYMbDMgFwywEyYBzMMzAzAYYmBYGYA' },
        { label: 'Open World', exportString: 'CsPAAAAAAAAAAAAAAAAAAAAAAMDYmZMzMDY2mZmZmZxMjMjxYYGgZmZmZmZmZAAAAAAAAAYMbDMgFwywEyYBzMzMzADADzMAzAD' },
      ],
      statPriority: [
        { stat: 'Strength' },
        { stat: 'Critical Strike' },
        { stat: 'Mastery' },
        { stat: 'Haste' },
        { stat: 'Versatility' },
      ],
      consumables: [
        { type: 'flask', name: 'Flask of the Shattered Sun' },
        { type: 'potion', name: "Light's Potential" },
        { type: 'food', subType: 'feast', name: "Hearty Silvermoon Parade/ Hearty Quel'dorei Medley" },
        { type: 'food', subType: 'personal', name: 'Royal Roast' },
        ...SHARED_CONSUMABLES,
      ],
      enchants: [
        { slot: 'Shoulders', name: "Enchant Shoulders - Akil'zon's Swiftness" },
        { slot: 'Chest', name: 'Enchant Chest - Mark of the Worldsoul' },
        { slot: 'Head', name: 'Enchant Helm - Empowered Blessing of Speed' },
        { slot: 'Legs', name: "Forest Hunter's Armor Kit" },
        { slot: 'Boots', name: "Enchant Boots - Farstrider's Hunt" },
        { slot: 'Ring', name: 'Enchant Ring - Eyes of the Eagle', note: 'both rings' },
      ],
      gems: [
        { socketType: 'Amethyst', name: 'Flawless Deadly Amethyst' },
        { socketType: 'Garnet', name: 'Flawless Masterful Garnet' },
        { socketType: 'Peridot', name: 'Flawless Deadly Peridot' },
        { socketType: 'Lapid', name: 'Flawless Deadly Lapis' },
      ],
    },

    {
      specName: 'Unholy',
      patch: '12.0.5',
      season: 'Midnight Season 1',
      lastUpdated: '2026-04-26',
      links: {
        cheatSheet: 'https://www.wowhead.com/guide/classes/death-knight/unholy/cheat-sheet',
        talents: 'https://www.wowhead.com/guide/classes/death-knight/unholy/talent-builds-pve-dps',
        rotation: 'https://www.wowhead.com/guide/classes/death-knight/unholy/rotation-cooldowns-pve-dps',
        statPriority: 'https://www.wowhead.com/guide/classes/death-knight/unholy/stat-priority-pve-dps',
        consumables: 'https://www.wowhead.com/guide/classes/death-knight/unholy/enchants-gems-pve-dps',
        bisGear: 'https://www.wowhead.com/guide/classes/death-knight/unholy/bis-gear',
        overview: 'https://www.wowhead.com/guide/classes/death-knight/unholy/overview-pve-dps',
      },
      talentLoadouts: [
        { label: 'Raid', exportString: 'CwPAAAAAAAAAAAAAAAAAAAAAAAwMjZMDDz2MzMTzmZmZMjBAAAAAAAgZGmZAw2MmZ2mZGjZAbmFDDZgZjhGLAYGAGzMjZAmZmxYA' },
        { label: 'Mythic+', exportString: 'CwPAAAAAAAAAAAAAAAAAAAAAAAYmhZMDDz2MzMTzmxMzMjBAAAAAAAgZGzYAwyMmZ2MzYMDYzsZYIDMbM0YBDYGAGzMjZAmZmxYA' },
        { label: 'Open World', exportString: 'CwPAAAAAAAAAAAAAAAAAAAAAAAwMjZMDDz2MzMTzmZmZMjBAAAAAAAgZGzYAw2MmZ2mZGjZAbmNDDZgZhhGLYAzAAzMjZAmZmxYA' },
      ],
      statPriority: [
        { stat: 'Strength' },
        { stat: 'Mastery' },
        { stat: 'Critical Strike' },
        { stat: 'Haste' },
        { stat: 'Versatility' },
      ],
      consumables: [
        { type: 'flask', name: 'Flask of the Shattered Sun' },
        { type: 'potion', name: 'Potion of Recklessness' },
        { type: 'food', subType: 'feast', name: 'Silvermoon Parade' },
        { type: 'food', subType: 'personal', name: 'Royal Roast' },
        ...SHARED_CONSUMABLES,
      ],
      enchants: [
        { slot: 'Weapon', name: 'Rune of the Apocalypse' },
        { slot: 'Chest', name: 'Enchant Chest - Mark of the Worldsoul' },
        { slot: 'Legs', name: "Forest Hunter's Armor Kit" },
        { slot: 'Boots', name: "Enchant Boots - Farstrider's Hunt" },
        { slot: 'Ring', name: 'Enchant Ring - Eyes of the Eagle', note: 'both rings' },
      ],
      gems: [
        { socketType: 'Diamond', name: 'Indecipherable Eversong Diamond' },
        { socketType: 'Garnet', name: 'Flawless Masterful Garnet' },
        { socketType: 'Amethyst', name: 'Flawless Deadly Amethyst' },
      ],
    },

  ],
};

export default deathknightGuide;
