// Auto-generated by wowhead-data-scraper on 2026-04-26. Review before committing.
import type { ClassGuide, Consumable } from './types';

const SHARED_CONSUMABLES: Consumable[] = [
  { type: 'healthPotion', name: 'Silvermoon Health Potion' },
  { type: 'augmentRune', name: 'Void-Touched Augment Rune' },
];

const demonhunterGuide: ClassGuide = {
  className: 'Demon Hunter',
  wowClass: 'demonhunter',
  specs: [
    {
      specName: 'Havoc',
      patch: '12.0.5',
      season: 'Midnight Season 1',
      lastUpdated: '2026-04-26',
      links: {
        cheatSheet: 'https://www.wowhead.com/guide/classes/demon-hunter/havoc/cheat-sheet',
        talents: 'https://www.wowhead.com/guide/classes/demon-hunter/havoc/talent-builds-pve-dps',
        rotation: 'https://www.wowhead.com/guide/classes/demon-hunter/havoc/rotation-cooldowns-pve-dps',
        statPriority: 'https://www.wowhead.com/guide/classes/demon-hunter/havoc/stat-priority-pve-dps',
        consumables: 'https://www.wowhead.com/guide/classes/demon-hunter/havoc/enchants-gems-pve-dps',
        bisGear: 'https://www.wowhead.com/guide/classes/demon-hunter/havoc/bis-gear',
        overview: 'https://www.wowhead.com/guide/classes/demon-hunter/havoc/overview-pve-dps',
      },
      talentLoadouts: [
        { label: 'Raid', exportString: 'CEkAAAAAAAAAAAAAAAAAAAAAAYGMzMzmxMzMmZmMmZAAAAAAAzyDMmtZYmZ2mZGbz28AzwYYsMw2sYGDzmmGzMjhNAAAAAAAAmZwAAAAwA' },
        { label: 'Mythic+', exportString: 'CEkAAAAAAAAAAAAAAAAAAAAAAYmZmZmZ2mxMzMGzkxMDAAAAAAYWMmtZYmBmx2sNzMjxALDsNbmxwsopxMzYGbAAAADAAAgZGMAAAAM' },
        { label: 'Open World', exportString: 'CEkAAAAAAAAAAAAAAAAAAAAAAYmZmZmZ2mxMzMGzkxMDAAAAAAYWMmtZYmBmx2sNzMjxALDsNbmxwsopxMzYGbAAAADAAAgZGMAAAAM' },
      ],
      statPriority: [
        { stat: 'Agility' },
        { stat: 'Critical Strike' },
        { stat: 'Mastery' },
        { stat: 'Haste' },
        { stat: 'Versatility' },
      ],
      consumables: [
        { type: 'flask', name: 'Flask of the Shattered Sun' },
        { type: 'potion', name: "Potion of Recklessness or Light's Potential" },
        { type: 'food', subType: 'feast', name: 'Hearty Harandar Celebration' },
        { type: 'food', subType: 'personal', name: 'Royal Roast / Hearty Royal Roast' },
        ...SHARED_CONSUMABLES,
      ],
      enchants: [
        { slot: 'Weapon', name: "Enchant Weapon - Acuity of the Ren'dorei" },
        { slot: 'Helm', name: 'Enchant Helm - Empowered Rune of Avoidance' },
        { slot: 'Chest', name: 'Enchant Chest - Mark of the Worldsoul' },
        { slot: 'Legs', name: "Forest Hunter's Armor Kit" },
        { slot: 'Boots', name: "Enchant Boots - Lynx's Dexterity" },
        { slot: 'Ring', name: 'Enchant Ring - Eyes of the Eagle', note: 'both rings' },
      ],
      gems: [
        { socketType: 'Diamond', name: 'Indecipherable Eversong Diamond' },
        { socketType: 'Garnet', name: 'Flawless Masterful Garnet' },
      ],
    },

    {
      specName: 'Vengeance',
      patch: '12.0.5',
      season: 'Midnight Season 1',
      lastUpdated: '2026-04-26',
      links: {
        cheatSheet: 'https://www.wowhead.com/guide/classes/demon-hunter/vengeance/cheat-sheet',
        talents: 'https://www.wowhead.com/guide/classes/demon-hunter/vengeance/talent-builds-pve-tank',
        rotation: 'https://www.wowhead.com/guide/classes/demon-hunter/vengeance/rotation-cooldowns-pve-tank',
        statPriority: 'https://www.wowhead.com/guide/classes/demon-hunter/vengeance/stat-priority-pve-tank',
        consumables: 'https://www.wowhead.com/guide/classes/demon-hunter/vengeance/enchants-gems-pve-tank',
        bisGear: 'https://www.wowhead.com/guide/classes/demon-hunter/vengeance/bis-gear',
        overview: 'https://www.wowhead.com/guide/classes/demon-hunter/vengeance/overview-pve-tank',
      },
      talentLoadouts: [
        { label: 'Raid', exportString: 'CUkAAAAAAAAAAAAAAAAAAAAAAAAYMzMjZmZkZmZYWMzMjhZMzYGzYmZYGmx2MzYMAAAAAAAQAzMjNAAAAMYMzMzs02MzMAwAAAAYA' },
        { label: 'Mythic+', exportString: 'CUkAAAAAAAAAAAAAAAAAAAAAAAAYMzMjhZkZmBWMjZwMjZGz8AzMzYYmtZGbjZMGzAAAAAAAIgZmxGAAAAGYmZmZWabmZGAMDAAAgB' },
        { label: 'Open World', exportString: 'CUkAAAAAAAAAAAAAAAAAAAAAAAAYMzMjxMjMzMwiZMDmZMzYmHYGzYMzsNzYbMDGzAAAAAAAIgZmxGAAAAGMzMzMzSbzMzAADAAAgB' },
      ],
      statPriority: [
        { stat: 'Agility' },
        { stat: 'Haste' },
        { stat: 'Critical Strike' },
        { stat: 'Versatility' },
        { stat: 'Mastery' },
      ],
      consumables: [
        { type: 'flask', name: 'Flask of the Blood Knights' },
        { type: 'potion', name: "Light's Potential" },
        { type: 'weaponBuff', name: 'Thalassian Phoenix Oil' },
        ...SHARED_CONSUMABLES,
      ],
      enchants: [
        { slot: 'Helm', name: 'Enchant Helm - Empowered Blessing of Speed' },
        { slot: 'Chest', name: 'Enchant Chest - Mark of the Worldsoul' },
        { slot: 'Shoulders', name: "Enchant Shoulders - Akil'zon's Swiftness" },
        { slot: 'Legs', name: "Forest Hunter's Armor Kit" },
        { slot: 'Boots', name: "Enchant Boots - Farstrider's Hunt" },
        { slot: 'Ring', name: 'Enchant Ring - Eyes of the Eagle', note: 'both rings' },
      ],
      gems: [
        { socketType: 'Peridot', name: 'Flawless Versatile Peridot' },
        { socketType: 'Lapis', name: 'Flawless Quick Lapis' },
        { socketType: 'Garnet', name: 'Flawless Quick Garnet' },
        { socketType: 'Amethyst', name: 'Flawless Quick Amethyst' },
      ],
    },

    {
      specName: 'Devourer',
      patch: '12.0.5',
      season: 'Midnight Season 1',
      lastUpdated: '2026-04-26',
      links: {
        cheatSheet: 'https://www.wowhead.com/guide/classes/demon-hunter/devourer/cheat-sheet',
        talents: 'https://www.wowhead.com/guide/classes/demon-hunter/devourer/talent-builds-pve-dps',
        rotation: 'https://www.wowhead.com/guide/classes/demon-hunter/devourer/rotation-cooldowns-pve-dps',
        statPriority: 'https://www.wowhead.com/guide/classes/demon-hunter/devourer/stat-priority-pve-dps',
        consumables: 'https://www.wowhead.com/guide/classes/demon-hunter/devourer/enchants-gems-pve-dps',
        bisGear: 'https://www.wowhead.com/guide/classes/demon-hunter/devourer/bis-gear',
        overview: 'https://www.wowhead.com/guide/classes/demon-hunter/devourer/overview-pve-dps',
      },
      talentLoadouts: [
        { label: 'Raid', exportString: 'CgcBAAAAAAAAAAAAAAAAAAAAAAA2MmZmZmZmxwMAAAAAAAegxsNYGAAAAAAAAmxMMzMzMzMzMDzsYGjFZhZmZmt2mZmBwwAQgZMYMD' },
        { label: 'Mythic+', exportString: 'CgcBAAAAAAAAAAAAAAAAAAAAAAA2mxMzMzMzMGmBAAAAAAgxsNYGAAAAAAAAmxMMzMzMzMzMDzsYGjFZhZmZmt2mZmBwwAQgZMYMD' },
        { label: 'Open World', exportString: 'CgcBAAAAAAAAAAAAAAAAAAAAAAA2MmZmZmZmxwMAAAAAAAmxAmBAAAAAAAgZMDzMzMzMzMzwMbzMGbyGACYAGzMzsMzMNbzsNzMGzA' },
      ],
      statPriority: [
        { stat: 'Intellect' },
        { stat: 'Haste' },
        { stat: 'Mastery' },
        { stat: 'Critical Strike' },
        { stat: 'Versatility' },
      ],
      consumables: [
        { type: 'flask', name: 'Flask of the Magisters or Flask of the Blood Knights' },
        { type: 'potion', name: 'Potion of Recklessness' },
        { type: 'weaponBuff', name: 'Thalassian Phoenix Oil' },
        { type: 'food', subType: 'feast', name: 'Silvermoon Parade' },
        { type: 'food', subType: 'personal', name: 'Royal Roast' },
        ...SHARED_CONSUMABLES,
      ],
      enchants: [
        { slot: 'Helm', name: 'Enchant Helm - Empowered Rune of Avoidance' },
        { slot: 'Chest', name: 'Enchant Chest - Mark of the Worldsoul' },
        { slot: 'Shoulders', name: "Enchant Shoulders - Amirdrassil's Grace" },
        { slot: 'Legs', name: 'Sunfire Silk Spellthread' },
        { slot: 'Boots', name: "Enchant Boots - Lynx's Dexterity" },
        { slot: 'Ring', name: 'Enchant Ring - Eyes of the Eagle', note: 'both rings' },
      ],
      gems: [
        { socketType: 'Diamond', name: 'Indecipherable Eversong Diamond' },
        { socketType: 'Amethyst', name: 'Flawless Quick Amethyst' },
      ],
    },

  ],
};

export default demonhunterGuide;
