// Auto-generated by wowhead-data-scraper on 2026-04-26. Review before committing.
import type { ClassGuide, Consumable } from './types';

const SHARED_CONSUMABLES: Consumable[] = [
  { type: 'healthPotion', name: 'Silvermoon Health Potion' },
  { type: 'augmentRune', name: 'Void-Touched Augment Rune' },
];

const druidGuide: ClassGuide = {
  className: 'Druid',
  wowClass: 'druid',
  specs: [
    {
      specName: 'Balance',
      patch: '12.0.5',
      season: 'Midnight Season 1',
      lastUpdated: '2026-04-26',
      links: {
        cheatSheet: 'https://www.wowhead.com/guide/classes/druid/balance/cheat-sheet',
        talents: 'https://www.wowhead.com/guide/classes/druid/balance/talent-builds-pve-dps',
        rotation: 'https://www.wowhead.com/guide/classes/druid/balance/rotation-cooldowns-pve-dps',
        statPriority: 'https://www.wowhead.com/guide/classes/druid/balance/stat-priority-pve-dps',
        consumables: 'https://www.wowhead.com/guide/classes/druid/balance/enchants-gems-pve-dps',
        bisGear: 'https://www.wowhead.com/guide/classes/druid/balance/bis-gear',
        overview: 'https://www.wowhead.com/guide/classes/druid/balance/overview-pve-dps',
      },
      talentLoadouts: [
        { label: 'Raid', exportString: 'CYGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWoMbNjxMDMmlZmZmBYYWmZbYGzYjlZMzMjZ2wAgBYZbshpZmlRAAAA2MzMzMYzYYMDgZGAYA' },
        { label: 'Mythic+', exportString: 'CYGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWoMbNMmZgxsMzMzMLMgZZmlZWMzMWYZmlxMjxGGAMW2mZwY2GBmAAAAswMzMD2MmxYAAYmBGA' },
        { label: 'Open World', exportString: 'CYGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWoMbNMmZgxsMzMzMLMgZZmlx2MmxGLzYmZGmFMAYAW2GbYamZbEAAAgNmZmZwmxMGzAYmBAGA' },
      ],
      statPriority: [
        { stat: 'Intellect' },
        { stat: 'Mastery' },
        { stat: 'Critical Strike' },
        { stat: 'Haste' },
        { stat: 'Versatility' },
      ],
      consumables: [
        { type: 'flask', name: 'Flask of the Magisters' },
        { type: 'potion', name: "Light's Potential Draught of Rampant Abandon" },
        { type: 'weaponBuff', name: 'Thalassian Phoenix Oil' },
        { type: 'food', subType: 'feast', name: 'Harandar Celebration' },
        { type: 'food', subType: 'personal', name: 'Impossibly Royal Roast' },
        ...SHARED_CONSUMABLES,
      ],
      enchants: [
        { slot: 'Weapon', name: "Enchant Weapon - Acuity of the Ren'dorei" },
        { slot: 'Head', name: 'Enchant Helm - Empowered Rune of Avoidance' },
        { slot: 'Shoulders', name: "Enchant Shoulders - Amirdrassil's Grace" },
        { slot: 'Chest', name: 'Enchant Chest - Mark of the Worldsoul' },
        { slot: 'Legs', name: 'Sunfire Silk Spellthread' },
        { slot: 'Boots', name: "Enchant Boots - Lynx's Dexterity" },
        { slot: 'Ring', name: 'Enchant Ring - Eyes of the Eagle', note: 'both rings' },
      ],
      gems: [
        { socketType: 'Garnet', name: 'Flawless Masterful Garnet' },
        { socketType: 'Peridot', name: 'Flawless Masterful Peridot' },
        { socketType: 'Amethyst', name: 'Flawless Quick Amethyst' },
        { socketType: 'Lapis', name: 'Flawless Masterful Lapis' },
      ],
    },

    {
      specName: 'Feral',
      patch: '12.0.5',
      season: 'Midnight Season 1',
      lastUpdated: '2026-04-26',
      links: {
        cheatSheet: 'https://www.wowhead.com/guide/classes/druid/feral/cheat-sheet',
        talents: 'https://www.wowhead.com/guide/classes/druid/feral/talent-builds-pve-dps',
        rotation: 'https://www.wowhead.com/guide/classes/druid/feral/rotation-cooldowns-pve-dps',
        statPriority: 'https://www.wowhead.com/guide/classes/druid/feral/stat-priority-pve-dps',
        consumables: 'https://www.wowhead.com/guide/classes/druid/feral/enchants-gems-pve-dps',
        bisGear: 'https://www.wowhead.com/guide/classes/druid/feral/bis-gear',
        overview: 'https://www.wowhead.com/guide/classes/druid/feral/overview-pve-dps',
      },
      talentLoadouts: [
        { label: 'Raid', exportString: 'CcGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjZwMzMzMmtlxyMbzYGzMDAAAALBzihxMjaGziZmZGjZYAAAAAAMwAAAAIAY2mZpZbmlNwMDwiZwAAYmBAD' },
        { label: 'Mythic+', exportString: 'CcGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAmZYmZmZMzsZsNz2MzMzDMzAAAAwSwsYMMzomxsYmZmZZMzAAAAAAgBAAAAoZWmtZmZABWAzMALMYAAAMzGG' },
        { label: 'Open World', exportString: 'CcGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAmZYmZmZMzsZsNz2MzMzDMzAAAAwSwsYMMzomxsYmZmZZMzAAAAAAgBAAAAoZWmtZmZABWAzMALMYAAAMzGG' },
      ],
      statPriority: [
        { stat: 'Agility' },
        { stat: 'Mastery' },
        { stat: 'Haste' },
        { stat: 'Critical Strike' },
        { stat: 'Versatility' },
      ],
      consumables: [
        { type: 'flask', name: 'Flask of the Shattered Sun (best) Flask of the Magisters (alternative)' },
        { type: 'potion', name: 'Draught of Rampant Abandon' },
        { type: 'food', subType: 'feast', name: 'Blooming Feast' },
        { type: 'food', subType: 'personal', name: 'Crimson Calamari' },
        ...SHARED_CONSUMABLES,
      ],
      enchants: [
        { slot: 'Head', name: 'Enchant Helm - Empowered Rune of Avoidance' },
        { slot: 'Shoulders', name: "Enchant Shoulders - Amirdrassil's Grace" },
        { slot: 'Chest', name: 'Enchant Chest - Mark of the Worldsoul' },
        { slot: 'Legs', name: "Forest Hunter's Armor Kit" },
        { slot: 'Boots', name: "Enchant Boots - Lynx's Dexterity" },
        { slot: 'Ring', name: 'Enchant Ring - Eyes of the Eagle', note: 'both rings' },
      ],
      gems: [
        { socketType: 'Amethyst', name: 'Flawless Quick Amethyst' },
        { socketType: 'Peridot', name: 'Flawless Masterful Peridot' },
        { socketType: 'Garnet', name: 'Flawless Masterful Garnet' },
        { socketType: 'Lapis', name: 'Flawless Masterful Lapis' },
      ],
    },

    {
      specName: 'Guardian',
      patch: '12.0.5',
      season: 'Midnight Season 1',
      lastUpdated: '2026-04-26',
      links: {
        cheatSheet: 'https://www.wowhead.com/guide/classes/druid/guardian/cheat-sheet',
        talents: 'https://www.wowhead.com/guide/classes/druid/guardian/talent-builds-pve-tank',
        rotation: 'https://www.wowhead.com/guide/classes/druid/guardian/rotation-cooldowns-pve-tank',
        statPriority: 'https://www.wowhead.com/guide/classes/druid/guardian/stat-priority-pve-tank',
        consumables: 'https://www.wowhead.com/guide/classes/druid/guardian/enchants-gems-pve-tank',
        bisGear: 'https://www.wowhead.com/guide/classes/druid/guardian/bis-gear',
        overview: 'https://www.wowhead.com/guide/classes/druid/guardian/overview-pve-tank',
      },
      talentLoadouts: [
        { label: 'Raid', exportString: 'CgGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgZmxsMmZMzmZZm5BMWGY2gRT0MzsMzMzMGzYGAAAAAwMWmBAAAgamlZZmZGAALYmBYxMYALYAwMbwA' },
        { label: 'Mythic+', exportString: 'CgGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgZmZmlhZMziZZMzMWGY2MMaimZmlZmZmZZMDAAAAAAzYZGwy2MDGzyAYKAAAwmxMPAwiZwAWwAMzAYA' },
        { label: 'Open World', exportString: 'CgGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgZmxsMmZMWMLzMPgZZZgZzMGNRzMziZmZmlxMAAAAAAMsMDYZbmBjZZAMFAAAYDz8ADYxMYwgltBYmBwA' },
      ],
      statPriority: [
        { stat: 'Agility' },
        { stat: 'Haste' },
        { stat: 'Versatility' },
        { stat: 'Critical Strike' },
        { stat: 'Mastery' },
      ],
      consumables: [
        { type: 'flask', name: 'Flask of the Blood Knights' },
        { type: 'potion', name: "Draught of Rampant Abandon or Light's Potential" },
        { type: 'weaponBuff', name: 'Thalassian Phoenix Oil' },
        ...SHARED_CONSUMABLES,
      ],
      enchants: [
        { slot: 'Weapon', name: "Enchant Weapon - Berserker's Rage" },
        { slot: 'Chest', name: 'Enchant Chest - Mark of the Worldsoul' },
        { slot: 'Head', name: 'Enchant Helm - Empowered Blessing of Speed' },
        { slot: 'Legs', name: "Forest Hunter's Armor Kit" },
        { slot: 'Boots', name: "Enchant Boots - Farstrider's Hunt" },
        { slot: 'Ring', name: "Enchant Ring - Silvermoon's Alacrity", note: 'both rings' },
      ],
      gems: [
        { socketType: 'Peridot', name: 'Flawless Versatile Peridot' },
      ],
    },

    {
      specName: 'Restoration',
      patch: '12.0.5',
      season: 'Midnight Season 1',
      lastUpdated: '2026-04-26',
      links: {
        cheatSheet: 'https://www.wowhead.com/guide/classes/druid/restoration/cheat-sheet',
        talents: 'https://www.wowhead.com/guide/classes/druid/restoration/talent-builds-pve-healer',
        rotation: 'https://www.wowhead.com/guide/classes/druid/restoration/rotation-cooldowns-pve-healer',
        statPriority: 'https://www.wowhead.com/guide/classes/druid/restoration/stat-priority-pve-healer',
        consumables: 'https://www.wowhead.com/guide/classes/druid/restoration/enchants-gems-pve-healer',
        bisGear: 'https://www.wowhead.com/guide/classes/druid/restoration/bis-gear',
        overview: 'https://www.wowhead.com/guide/classes/druid/restoration/overview-pve-healer',
      },
      talentLoadouts: [
        { label: 'Raid', exportString: 'CkGAAAAAAAAAAAAAAAAAAAAAAMjxMbz2MmZGz2wDwMzmxCzAAAAAAAAAAgtBNbMmmZM8AmlZmZmhhZAAAAAAAAAAEAAwsNzSz2Mb2YMzMMzAjmBAYmBgB' },
        { label: 'Mythic+', exportString: 'CkGAAAAAAAAAAAAAAAAAAAAAAMMmZZMjZmxsN8AMzsNjFbzAAAAAAAAAAgFDNbzw0MAmFzMzMLGGAAAAAMAAzAAQAAAz2MbNbzsYjZmZGMzGoZAAmZAYA' },
        { label: 'Open World', exportString: 'CkGAAAAAAAAAAAAAAAAAAAAAAMMmxYGzMjZbmZYYhZx2MAAAAAAAAAAYbQzmhpZMzYMLmZmZWmhxAAAAAAAYMAAEAAwsMzWzyML2gZeAMjFQzAAMzAwA' },
      ],
      statPriority: [
        { stat: 'Intellect' },
        { stat: 'Haste' },
        { stat: 'Mastery' },
        { stat: 'Versatility' },
        { stat: 'Critical Strike' },
      ],
      consumables: [
        { type: 'flask', name: 'Flask of the Blood Knights' },
        { type: 'potion', name: 'Potion of Recklessness (Preferred) / Lightfused Mana Potion (Situational)' },
        { type: 'weaponBuff', name: 'Thalassian Phoenix Oil' },
        { type: 'food', subType: 'feast', name: 'Harandar Celebration' },
        { type: 'food', subType: 'personal', name: 'Royal Roast' },
        ...SHARED_CONSUMABLES,
      ],
      enchants: [
        { slot: 'Weapon', name: "Enchant Weapon - Acuity of the Ren'dorei" },
        { slot: 'Helm', name: 'Enchant Helm - Empowered Hex of Leeching' },
        { slot: 'Shoulders', name: "Enchant Shoulders - Silvermoon's Mending" },
        { slot: 'Chest', name: 'Enchant Chest - Mark of the Worldsoul' },
        { slot: 'Legs', name: 'Arcanoweave Spellthread' },
        { slot: 'Boots', name: "Enchant Boots - Shaladrassil's Roots" },
        { slot: 'Ring', name: "Enchant Ring - Silvermoon's Alacrity", note: 'both rings' },
      ],
      gems: [
        { socketType: 'Diamond', name: 'Indecipherable Eversong Diamond' },
        { socketType: 'Peridot', name: 'Flawless Masterful Peridot' },
      ],
    },

  ],
};

export default druidGuide;
