// Auto-generated by wowhead-data-scraper on 2026-04-26. Review before committing.
import type { ClassGuide, Consumable } from './types';

const SHARED_CONSUMABLES: Consumable[] = [
  { type: 'healthPotion', name: 'Silvermoon Health Potion' },
  { type: 'weaponBuff', name: 'Thalassian Phoenix Oil' },
  { type: 'augmentRune', name: 'Void-Touched Augment Rune' },
];

const evokerGuide: ClassGuide = {
  className: 'Evoker',
  wowClass: 'evoker',
  specs: [
    {
      specName: 'Augmentation',
      patch: '12.0.5',
      season: 'Midnight Season 1',
      lastUpdated: '2026-04-26',
      links: {
        cheatSheet: 'https://www.wowhead.com/guide/classes/evoker/augmentation/cheat-sheet',
        talents: 'https://www.wowhead.com/guide/classes/evoker/augmentation/talent-builds-pve-dps',
        rotation: 'https://www.wowhead.com/guide/classes/evoker/augmentation/rotation-cooldowns-pve-dps',
        statPriority: 'https://www.wowhead.com/guide/classes/evoker/augmentation/stat-priority-pve-dps',
        consumables: 'https://www.wowhead.com/guide/classes/evoker/augmentation/enchants-gems-pve-dps',
        bisGear: 'https://www.wowhead.com/guide/classes/evoker/augmentation/bis-gear',
        overview: 'https://www.wowhead.com/guide/classes/evoker/augmentation/overview-pve-dps',
      },
      talentLoadouts: [
        { label: 'Raid', exportString: 'CEcBAAAAAAAAAAAAAAAAAAAAAMmZmZbmZmxyAzsMjxwMAAAAAgBAAzMDMYM1YmZGAAAAMjZmxMzyYmBmZzYwCsMGGbDgZiYDzMwMDgB' },
        { label: 'Mythic+', exportString: 'CEcBAAAAAAAAAAAAAAAAAAAAAMmZmZbmZmxyAzsMjxwMAAAAAAAAYmBmBjHoGzMzAAAAgZmZmxMz2YmBmZzYwCsMGGbDgZiYDzMDmZAM' },
        { label: 'Open World', exportString: 'CEcBAAAAAAAAAAAAAAAAAAAAAMmZmZbmZmxyAzsMjxwMAAAAAAAAYmBmBjHoGzMzAAAAgZmZmxMzyYmBmZzYwCsMGGbDgZiYDzMDmZAM' },
      ],
      statPriority: [
        { stat: 'Intellect' },
        { stat: 'Critical Strike' },
        { stat: 'Haste' },
        { stat: 'Mastery' },
        { stat: 'Versatility' },
      ],
      consumables: [
        { type: 'flask', name: 'Flask of the Shattered Sun' },
        { type: 'potion', name: "Light's Potential" },
        { type: 'food', subType: 'feast', name: 'Hearty Silvermoon Parade' },
        { type: 'food', subType: 'personal', name: 'Hearty Royal Roast' },
        ...SHARED_CONSUMABLES,
      ],
      enchants: [
        { slot: 'Weapon', name: "Enchant Weapon - Acuity of the Ren'dorei" },
        { slot: 'Helm', name: 'Enchant Helm - Empowered Rune of Avoidance' },
        { slot: 'Shoulders', name: "Enchant Shoulders - Amirdrassil's Grace" },
        { slot: 'Chest', name: 'Enchant Chest - Mark of the Worldsoul' },
        { slot: 'Legs', name: 'Sunfire Silk Spellthread' },
        { slot: 'Boots', name: "Enchant Boots - Lynx's Dexterity" },
        { slot: 'Ring', name: "Enchant Ring - Nature's Fury", note: 'both rings' },
      ],
      gems: [
        { socketType: 'Diamond', name: 'Indecipherable Eversong Diamond' },
        { socketType: 'Garnet', name: 'Flawless Quick Garnet' },
      ],
    },

    {
      specName: 'Devastation',
      patch: '12.0.5',
      season: 'Midnight Season 1',
      lastUpdated: '2026-04-26',
      links: {
        cheatSheet: 'https://www.wowhead.com/guide/classes/evoker/devastation/cheat-sheet',
        talents: 'https://www.wowhead.com/guide/classes/evoker/devastation/talent-builds-pve-dps',
        rotation: 'https://www.wowhead.com/guide/classes/evoker/devastation/rotation-cooldowns-pve-dps',
        statPriority: 'https://www.wowhead.com/guide/classes/evoker/devastation/stat-priority-pve-dps',
        consumables: 'https://www.wowhead.com/guide/classes/evoker/devastation/enchants-gems-pve-dps',
        bisGear: 'https://www.wowhead.com/guide/classes/evoker/devastation/bis-gear',
        overview: 'https://www.wowhead.com/guide/classes/evoker/devastation/overview-pve-dps',
      },
      talentLoadouts: [
        { label: 'Raid', exportString: 'CsbBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzMDMDzYmBMYMTzMzMNjx2MmZmZmHYmZGwMmxYmZZmZgBGDWglxox2AyMIYDDMzghB' },
        { label: 'Mythic+', exportString: 'CsbBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzMDgZGmBGGjZaMzMNDz2MmZmZmZmZGwMzMGzMLzMDMwYwCsMGN2GQmBBbYGMzghB' },
        { label: 'Open World', exportString: 'CsbBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwMzMDMDzMMwwYMTjZmpZMzyMmZmZGzMzAmZGDzMLzMDMADWglxox2AyMIYDDMzgZMA' },
      ],
      statPriority: [
        { stat: 'Intellect' },
        { stat: 'Critical Strike' },
        { stat: 'Haste' },
        { stat: 'Mastery' },
        { stat: 'Versatility' },
      ],
      consumables: [
        { type: 'flask', name: 'Flask of the Shattered Sun Flask of the Magisters' },
        { type: 'potion', name: 'Potion of Recklessness' },
        { type: 'food', subType: 'feast', name: "Harandar Celebration and Quel'dorei Medley are equal" },
        { type: 'food', subType: 'personal', name: "Champion's Bento" },
        ...SHARED_CONSUMABLES,
      ],
      enchants: [
        { slot: 'Weapon', name: "Enchant Weapon - Acuity of the Ren'dorei" },
        { slot: 'Head', name: 'Enchant Helm - Empowered Rune of Avoidance' },
        { slot: 'Shoulders', name: "Enchant Shoulders - Amirdrassil's Grace" },
        { slot: 'Chest', name: 'Enchant Chest - Mark of the Worldsoul' },
        { slot: 'Legs', name: 'Sunfire Silk Spellthread' },
        { slot: 'Boots', name: "Enchant Boots - Lynx's Dexterity" },
      ],
      gems: [
        { socketType: 'Peridot', name: 'Flawless Deadly Peridot' },
        { socketType: 'Amethyst', name: 'Flawless Deadly Amethyst' },
        { socketType: 'Garnet', name: 'Flawless Quick Garnet' },
        { socketType: 'Lapis', name: 'Flawless Deadly Lapis' },
      ],
    },

    {
      specName: 'Preservation',
      patch: '12.0.5',
      season: 'Midnight Season 1',
      lastUpdated: '2026-04-26',
      links: {
        cheatSheet: 'https://www.wowhead.com/guide/classes/evoker/preservation/cheat-sheet',
        talents: 'https://www.wowhead.com/guide/classes/evoker/preservation/talent-builds-pve-healer',
        rotation: 'https://www.wowhead.com/guide/classes/evoker/preservation/rotation-cooldowns-pve-healer',
        statPriority: 'https://www.wowhead.com/guide/classes/evoker/preservation/stat-priority-pve-healer',
        consumables: 'https://www.wowhead.com/guide/classes/evoker/preservation/enchants-gems-pve-healer',
        bisGear: 'https://www.wowhead.com/guide/classes/evoker/preservation/bis-gear',
        overview: 'https://www.wowhead.com/guide/classes/evoker/preservation/overview-pve-healer',
      },
      talentLoadouts: [
        { label: 'Raid', exportString: 'CwbBAAAAAAAAAAAAAAAAAAAAAAAAAAAYmZ2WmHADzMmNjZmZWmxAAAzYGDmxMyMzAAAAMzMTmxMjZbmZAwAjZsxCMwMaoBsAjZGgxA' },
        { label: 'Mythic+', exportString: 'CwbBAAAAAAAAAAAAAAAAAAAAAAAAAAAegZmZ2WGYYmxsZGjx2wAAAzYmZmZMMTMmBAAA2mZmJjZmZGjZAAYMjNWgBmRDNMsAzMzAwA' },
        { label: 'Open World', exportString: 'CwbBAAAAAAAAAAAAAAAAAAAAAAAAAAAmZmZ2MwYmZGMzMDbAAAYYMDzYGZmZAAAALzMz0MGzMjZmBAgxM2YDGYGN0gxCMmZAmZA' },
      ],
      statPriority: [
        { stat: 'Intellect' },
        { stat: 'Mastery' },
        { stat: 'Critical Strike' },
        { stat: 'Haste' },
        { stat: 'Versatility' },
      ],
      consumables: [
        { type: 'flask', name: 'Flask of the Magisters' },
        { type: 'potion', name: 'Potion of Recklessness (Preferred) / Lightfused Mana Potion (Situational)' },
        { type: 'food', subType: 'feast', name: 'Harandar Celebration' },
        { type: 'food', subType: 'personal', name: 'Royal Roast' },
        ...SHARED_CONSUMABLES,
      ],
      enchants: [
        { slot: 'Weapon', name: "Enchant Weapon - Acuity of the Ren'dorei" },
        { slot: 'Helm', name: 'Enchant Helm - Empowered Hex of Leeching' },
        { slot: 'Shoulders', name: "Enchant Shoulders - Silvermoon's Mending" },
        { slot: 'Chest', name: 'Enchant Chest - Mark of the Worldsoul' },
        { slot: 'Legs', name: 'Arcanoweave Spellthread' },
        { slot: 'Boots', name: "Enchant Boots - Shaladrassil's Roots" },
        { slot: 'Ring', name: "Enchant Ring - Zul'jin's Mastery", note: 'both rings' },
      ],
      gems: [
        { socketType: 'Diamond', name: 'Indecipherable Eversong Diamond' },
        { socketType: 'Amethyst', name: 'Flawless Quick Amethyst' },
      ],
    },

  ],
};

export default evokerGuide;
