// Auto-generated by wowhead-data-scraper on 2026-04-26. Review before committing.
import type { ClassGuide, Consumable } from './types';

const SHARED_CONSUMABLES: Consumable[] = [
  { type: 'potion', name: "Light's Potential" },
  { type: 'healthPotion', name: 'Silvermoon Health Potion' },
  { type: 'augmentRune', name: 'Void-Touched Augment Rune' },
];

const hunterGuide: ClassGuide = {
  className: 'Hunter',
  wowClass: 'hunter',
  specs: [
    {
      specName: 'Beast Mastery',
      patch: '12.0.5',
      season: 'Midnight Season 1',
      lastUpdated: '2026-04-26',
      links: {
        cheatSheet: 'https://www.wowhead.com/guide/classes/hunter/beast-mastery/cheat-sheet',
        talents: 'https://www.wowhead.com/guide/classes/hunter/beast-mastery/talent-builds-pve-dps',
        rotation: 'https://www.wowhead.com/guide/classes/hunter/beast-mastery/rotation-cooldowns-pve-dps',
        statPriority: 'https://www.wowhead.com/guide/classes/hunter/beast-mastery/stat-priority-pve-dps',
        consumables: 'https://www.wowhead.com/guide/classes/hunter/beast-mastery/enchants-gems-pve-dps',
        bisGear: 'https://www.wowhead.com/guide/classes/hunter/beast-mastery/bis-gear',
        overview: 'https://www.wowhead.com/guide/classes/hunter/beast-mastery/overview-pve-dps',
      },
      talentLoadouts: [
        { label: 'Raid', exportString: 'C0PAAAAAAAAAAAAAAAAAAAAAAAMmxwCsAzwQDbAAYG2GzsNzwMmZYYmxYmxMzYGzwMzYGzghmBAAAAwMAAAMzMzAMzGCDzCYbAA' },
        { label: 'Mythic+', exportString: 'C0PAAAAAAAAAAAAAAAAAAAAAAYzsNwAGwMsBZsAAgZGLzMDzwMzMYGzMzwMmZGzMzYbmZYMDLDNDAAAAgZAAAYegxMDzMABMLgtBA' },
        { label: 'Open World', exportString: 'C0PAAAAAAAAAAAAAAAAAAAAAAAMmxwGsAzwQDbAAYGzyMzsYGmZmZGzMMmxMMzMzYGmZGGzMMmmBAAAAAAAAMGzAMzCCWmZBsNA' },
      ],
      statPriority: [
        { stat: 'Agility' },
        { stat: 'Mastery' },
        { stat: 'Haste' },
        { stat: 'Critical Strike' },
        { stat: 'Versatility' },
      ],
      consumables: [
        { type: 'flask', name: 'Flask of the Magisters' },
        { type: 'weaponBuff', name: 'Thalassian Phoenix Oil' },
        ...SHARED_CONSUMABLES,
      ],
      enchants: [
        { slot: 'Weapon', name: "Enchant Weapon - Acuity of the Ren'dorei" },
        { slot: 'Head', name: 'Enchant Helm - Empowered Rune of Avoidance' },
        { slot: 'Shoulders', name: "Enchant Shoulders - Amirdrassil's Grace" },
        { slot: 'Chest', name: 'Enchant Chest - Mark of the Worldsoul' },
        { slot: 'Legs', name: "Forest Hunter's Armor Kit" },
        { slot: 'Boots', name: "Enchant Boots - Lynx's Dexterity" },
      ],
      gems: [
        { socketType: 'Diamond', name: 'Indecipherable Eversong Diamond' },
        { socketType: 'Amethyst', name: 'Flawless Quick Amethyst' },
        { socketType: 'Amethyst', name: 'Flawless Deadly Amethyst' },
        { socketType: 'Peridot', name: 'Flawless Masterful Peridot' },
      ],
    },

    {
      specName: 'Marksmanship',
      patch: '12.0.5',
      season: 'Midnight Season 1',
      lastUpdated: '2026-04-26',
      links: {
        cheatSheet: 'https://www.wowhead.com/guide/classes/hunter/marksmanship/cheat-sheet',
        talents: 'https://www.wowhead.com/guide/classes/hunter/marksmanship/talent-builds-pve-dps',
        rotation: 'https://www.wowhead.com/guide/classes/hunter/marksmanship/rotation-cooldowns-pve-dps',
        statPriority: 'https://www.wowhead.com/guide/classes/hunter/marksmanship/stat-priority-pve-dps',
        consumables: 'https://www.wowhead.com/guide/classes/hunter/marksmanship/enchants-gems-pve-dps',
        bisGear: 'https://www.wowhead.com/guide/classes/hunter/marksmanship/bis-gear',
        overview: 'https://www.wowhead.com/guide/classes/hunter/marksmanship/overview-pve-dps',
      },
      talentLoadouts: [
        { label: 'Raid', exportString: 'C4PAAAAAAAAAAAAAAAAAAAAAAwCMwMGNWGAzgNAAAAAAAAgZMjZwYmZMDGTzYYmttNzMzyMzMzMzCmlBzAAAmZmZMAmZabjFDwGzA' },
        { label: 'Mythic+', exportString: 'C4PAAAAAAAAAAAAAAAAAAAAAAYxsMwAmgZYLwsAAAAAAAAAMjZmZsZMzMmhlx0MGMLbMzMLzMzMzMLMzywMDAAwMGzMzMgJgBYjZA' },
        { label: 'Open World', exportString: 'C4PAAAAAAAAAAAAAAAAAAAAAAwCMwMGNWGAzgNAAAAAAAAgZMzMjNjHYmxMsMmmxgZbjZmxMzYmZ2YmthZGAAgZMmBwMTbwMAbMzMD' },
      ],
      statPriority: [
        { stat: 'Agility' },
        { stat: 'Critical Strike' },
        { stat: 'Mastery' },
        { stat: 'Versatility' },
        { stat: 'Haste' },
      ],
      consumables: [
        { type: 'flask', name: 'Flask of the Shattered Sun' },
        { type: 'weaponBuff', name: 'Thalassian Phoenix Oil' },
        { type: 'food', subType: 'feast', name: 'Hearty Harandar Celebration' },
        { type: 'food', subType: 'personal', name: 'Hearty Royal Roast' },
        ...SHARED_CONSUMABLES,
      ],
      enchants: [
        { slot: 'Weapon', name: "Enchant Weapon - Acuity of the Ren'dorei" },
        { slot: 'Helm', name: 'Enchant Helm - Empowered Hex of Leeching' },
        { slot: 'Shoulders', name: "Enchant Shoulders - Silvermoon's Mending" },
        { slot: 'Chest', name: 'Enchant Chest - Mark of the Worldsoul' },
        { slot: 'Legs', name: "Forest Hunter's Armor Kit" },
        { slot: 'Boots', name: "Enchant Boots - Shaladrassil's Roots" },
        { slot: 'Ring', name: 'Enchant Ring - Eyes of the Eagle', note: 'both rings' },
      ],
      gems: [
        { socketType: 'Peridot', name: 'Flawless Deadly Peridot' },
        { socketType: 'Amethyst', name: 'Flawless Deadly Amethyst' },
        { socketType: 'Garnet', name: 'Flawless Masterful Garnet' },
        { socketType: 'Lapis', name: 'Flawless Deadly Lapis' },
      ],
    },

    {
      specName: 'Survival',
      patch: '12.0.5',
      season: 'Midnight Season 1',
      lastUpdated: '2026-04-26',
      links: {
        cheatSheet: 'https://www.wowhead.com/guide/classes/hunter/survival/cheat-sheet',
        talents: 'https://www.wowhead.com/guide/classes/hunter/survival/talent-builds-pve-dps',
        rotation: 'https://www.wowhead.com/guide/classes/hunter/survival/rotation-cooldowns-pve-dps',
        statPriority: 'https://www.wowhead.com/guide/classes/hunter/survival/stat-priority-pve-dps',
        consumables: 'https://www.wowhead.com/guide/classes/hunter/survival/enchants-gems-pve-dps',
        bisGear: 'https://www.wowhead.com/guide/classes/hunter/survival/bis-gear',
        overview: 'https://www.wowhead.com/guide/classes/hunter/survival/overview-pve-dps',
      },
      talentLoadouts: [
        { label: 'Raid', exportString: 'C8PAAAAAAAAAAAAAAAAAAAAAAMgxMGWIbwMM0gFjZmZmxyAAAAAAgZMzMDz4BMjZwYaGAAAAAAjllZmZxMzMzYmxAmZDwsMjxM2MA' },
        { label: 'Mythic+', exportString: 'C8PAAAAAAAAAAAAAAAAAAAAAAMgxMG2ILwMM0gFzMzMzwyAAAAAAgZMzMjlZMmxMYMNDAAAADAMWWmZmFzMzYMmZAzsBAjxMzmBA' },
        { label: 'Open World', exportString: 'C8PAAAAAAAAAAAAAAAAAAAAAAMgxMG2ILwMM0gFzMzMzwyAAAAAAgZmZmZYGDjZGGTzAAAAwAAjllZmZxMzM8AjxAmZDAzYMzsZA' },
      ],
      statPriority: [
        { stat: 'Agility' },
        { stat: 'Mastery' },
        { stat: 'Haste' },
        { stat: 'Critical Strike' },
        { stat: 'Versatility' },
      ],
      consumables: [
        { type: 'flask', name: 'Fleeting Flask of the Magisters' },
        { type: 'weaponBuff', name: 'Adamantite Sharpening Stone(main hand)| Thalassian Phoenix Oil (off hand)' },
        ...SHARED_CONSUMABLES,
      ],
      enchants: [
        { slot: 'Weapon', name: "Enchant Weapon - Arcane Mastery (Main Hand / 2 Hand) | Enchant Weapon - Acuity of the Ren'dorei (Off Hand)" },
        { slot: 'Head', name: 'Enchant Helm - Empowered Rune of Avoidance' },
        { slot: 'Shoulders', name: "Enchant Shoulders - Amirdrassil's Grace" },
        { slot: 'Chest', name: 'Enchant Chest - Mark of the Worldsoul' },
        { slot: 'Legs', name: "Forest Hunter's Armor Kit" },
        { slot: 'Boots', name: "Enchant Boots - Lynx's Dexterity" },
      ],
      gems: [
        { socketType: 'Amethyst', name: 'Flawless Deadly Amethyst' },
      ],
    },

  ],
};

export default hunterGuide;
