// Auto-generated by wowhead-data-scraper on 2026-04-25. Review before committing.
import type { ClassGuide, Consumable } from './types';

const SHARED_CONSUMABLES: Consumable[] = [
  { type: 'healthPotion', name: 'Silvermoon Health Potion' },
  { type: 'weaponBuff', name: 'Thalassian Phoenix Oil' },
  { type: 'augmentRune', name: 'Void-Touched Augment Rune' },
];

const mageGuide: ClassGuide = {
  className: 'Mage',
  wowClass: 'mage',
  specs: [
    {
      specName: 'Arcane',
      patch: '12.0.5',
      season: 'Midnight Season 1',
      lastUpdated: '2026-04-25',
      links: {
        cheatSheet: 'https://www.wowhead.com/guide/classes/mage/arcane/cheat-sheet',
        talents: 'https://www.wowhead.com/guide/classes/mage/arcane/talent-builds-pve-dps',
        rotation: 'https://www.wowhead.com/guide/classes/mage/arcane/rotation-cooldowns-pve-dps',
        statPriority: 'https://www.wowhead.com/guide/classes/mage/arcane/stat-priority-pve-dps',
        consumables: 'https://www.wowhead.com/guide/classes/mage/arcane/enchants-gems-pve-dps',
        bisGear: 'https://www.wowhead.com/guide/classes/mage/arcane/bis-gear',
        overview: 'https://www.wowhead.com/guide/classes/mage/arcane/overview-pve-dps',
      },
      talentLoadouts: [
        { label: 'Raid', exportString: 'C4DAAAAAAAAAAAAAAAAAAAAAAYGGLzMzswMzQzMzAAAwAAgAmZmZZZmZYBAgtxMzMmtFLzMzYmxYMzMGLMzMjZAAGAAAzsAAmBADD' },
        { label: 'Mythic+', exportString: 'C4DAAAAAAAAAAAAAAAAAAAAAAMzwYZmZmFmZGamxAAAwAAgAmZmZZZmJWAAYbGzMjZzsMzMjZGjhZmZswMzMmBAYAAAMzCAYGAMM' },
        { label: 'Open World', exportString: 'C4DAAAAAAAAAAAAAAAAAAAAAAMzwYZmZmFmZGamxAAAwAAgAmZmZZZmJWAAYbGzMjZzsMzMjZGjhZmZswMzMmBAYAAAMzCAYGAMM' },
      ],
      statPriority: [
        { stat: 'Intellect' },
        { stat: 'Mastery' },
        { stat: 'Haste' },
        { stat: 'Critical Strike' },
        { stat: 'Versatility' },
      ],
      consumables: [
        { type: 'flask', name: 'Flask of Thalassian Resistance' },
        { type: 'potion', name: "Light's Potential" },
        { type: 'food', subType: 'feast', name: 'Silvermoon Parade' },
        { type: 'food', subType: 'personal', name: 'Anything that gives max stats is basically useable, sim for best results!' },
        ...SHARED_CONSUMABLES,
      ],
      enchants: [
        { slot: 'Weapon', name: "Enchant Weapon - Acuity of the Ren'dorei" },
        { slot: 'Head', name: 'Enchant Helm - Empowered Rune of Avoidance' },
        { slot: 'Shoulders', name: "Enchant Shoulders - Silvermoon's Mending" },
        { slot: 'Chest', name: 'Enchant Chest - Mark of the Worldsoul' },
        { slot: 'Legs', name: 'Arcanoweave Spellthread' },
        { slot: 'Boots', name: "Enchant Boots - Shaladrassil's Roots" },
        { slot: 'Ring', name: 'Enchant Ring - Eyes of the Eagle', note: 'both rings' },
      ],
      gems: [
        { socketType: 'Amethyst', name: 'Flawless Quick Amethyst' },
        { socketType: 'Peridot', name: 'Flawless Masterful Peridot' },
        { socketType: 'Garnet', name: 'Flawless Masterful Garnet' },
        { socketType: 'Lapis', name: 'Flawless Masterful Lapis' },
      ],
    },

    {
      specName: 'Fire',
      patch: '12.0.5',
      season: 'Midnight Season 1',
      lastUpdated: '2026-04-25',
      links: {
        cheatSheet: 'https://www.wowhead.com/guide/classes/mage/fire/cheat-sheet',
        talents: 'https://www.wowhead.com/guide/classes/mage/fire/talent-builds-pve-dps',
        rotation: 'https://www.wowhead.com/guide/classes/mage/fire/rotation-cooldowns-pve-dps',
        statPriority: 'https://www.wowhead.com/guide/classes/mage/fire/stat-priority-pve-dps',
        consumables: 'https://www.wowhead.com/guide/classes/mage/fire/enchants-gems-pve-dps',
        bisGear: 'https://www.wowhead.com/guide/classes/mage/fire/bis-gear',
        overview: 'https://www.wowhead.com/guide/classes/mage/fire/overview-pve-dps',
      },
      talentLoadouts: [
        { label: 'Raid', exportString: 'C8DAAAAAAAAAAAAAAAAAAAAAAYGGLzMzswMDZmZGAAAGAwMz0sssMDAwmZmx2YmZGAAAAAgFzMzMDAAGzwYmZmZ2GAmZIjxYwMMA' },
        { label: 'Mythic+', exportString: 'C8DAAAAAAAAAAAAAAAAAAAAAAYGGLzMzswMDZmZGAAAmZZGzMLzCEAAwiZmx2YmZGAAAAAgFzMzMDAAGzYmZmZmZ2AmZADzYMYwA' },
        { label: 'Open World', exportString: 'C8DAAAAAAAAAAAAAAAAAAAAAAMzwMLzMzsgZGZmxAAAwAAmZmmlltZAA2MzM2GzMzYDAAAAAWMzMzMAAYMDjZmZmZbAYmhwYMYGG' },
      ],
      statPriority: [
        { stat: 'Intellect' },
        { stat: 'Haste' },
        { stat: 'Mastery' },
        { stat: 'Versatility' },
        { stat: 'Critical Strike' },
      ],
      consumables: [
        { type: 'flask', name: 'Flask of the Magisters Flask of the Blood Knights' },
        { type: 'potion', name: "Light's Potential" },
        ...SHARED_CONSUMABLES,
      ],
      enchants: [
        { slot: 'Weapon', name: "Enchant Weapon - Acuity of the Ren'dorei" },
        { slot: 'Head', name: 'Enchant Helm - Empowered Rune of Avoidance' },
        { slot: 'Shoulders', name: "Enchant Shoulders - Amirdrassil's Grace" },
        { slot: 'Chest', name: 'Enchant Chest - Mark of the Worldsoul' },
        { slot: 'Legs', name: 'Sunfire Silk Spellthread' },
        { slot: 'Boots', name: "Enchant Boots - Lynx's Dexterity" },
      ],
      gems: [
        { socketType: 'Peridot', name: 'Flawless Masterful Peridot' },
        { socketType: 'Amethyst', name: 'Flawless Quick Amethyst' },
        { socketType: 'Garnet', name: 'Flawless Quick Garnet' },
        { socketType: 'Lapis', name: 'Flawless Quick Lapis' },
      ],
    },

    {
      specName: 'Frost',
      patch: '12.0.5',
      season: 'Midnight Season 1',
      lastUpdated: '2026-04-25',
      links: {
        cheatSheet: 'https://www.wowhead.com/guide/classes/mage/frost/cheat-sheet',
        talents: 'https://www.wowhead.com/guide/classes/mage/frost/talent-builds-pve-dps',
        rotation: 'https://www.wowhead.com/guide/classes/mage/frost/rotation-cooldowns-pve-dps',
        statPriority: 'https://www.wowhead.com/guide/classes/mage/frost/stat-priority-pve-dps',
        consumables: 'https://www.wowhead.com/guide/classes/mage/frost/enchants-gems-pve-dps',
        bisGear: 'https://www.wowhead.com/guide/classes/mage/frost/bis-gear',
        overview: 'https://www.wowhead.com/guide/classes/mage/frost/overview-pve-dps',
      },
      talentLoadouts: [
        { label: 'Raid', exportString: 'CAEAAAAAAAAAAAAAAAAAAAAAAYGGLzMzsMmZmYmxMjZMziZmZmZMDAAAMzMzyyMTbAAAAAAgNA22GzMzgZZeAjZYBAAgZWAmJjBMDGA' },
        { label: 'Mythic+', exportString: 'CAEAAAAAAAAAAAAAAAAAAAAAAMzwYZmZmFmZmYGmZmZmZWMzMMjZAAAgZmZWWmZaDAAWAAAAWAYbbMzMDmthxMjNAAAmZDYmMGwMYA' },
        { label: 'Open World', exportString: 'CAEAAAAAAAAAAAAAAAAAAAAAAYGGLzMzswMzEzMzMzMzMziZmhZMDAAAMzMzyyMTbAAAAAAgFA22GzMzgZbYMzYDAAgZ2AmJjBMDGA' },
      ],
      statPriority: [
        { stat: 'Intellect' },
        { stat: 'Mastery' },
        { stat: 'Critical Strike' },
        { stat: 'Haste' },
        { stat: 'Versatility' },
      ],
      consumables: [
        { type: 'flask', name: 'Flask of the Magisters' },
        { type: 'potion', name: "Light's Potential / Potion of Recklessness" },
        { type: 'food', subType: 'feast', name: 'Harandar Celebration' },
        { type: 'food', subType: 'personal', name: "Champion's Bento" },
        ...SHARED_CONSUMABLES,
      ],
      enchants: [
        { slot: 'Weapon', name: "Enchant Weapon - Acuity of the Ren'dorei" },
        { slot: 'Head', name: 'Enchant Helm - Empowered Rune of Avoidance' },
        { slot: 'Shoulders', name: "Enchant Shoulders - Amirdrassil's Grace" },
        { slot: 'Chest', name: 'Enchant Chest - Mark of the Worldsoul' },
        { slot: 'Legs', name: 'Sunfire Silk Spellthread' },
        { slot: 'Boots', name: "Enchant Boots - Lynx's Dexterity" },
        { slot: 'Ring', name: 'Formula: Enchant Ring - Eyes of the Eagle', note: 'both rings' },
      ],
      gems: [
        { socketType: 'Amethyst', name: 'Flawless Deadly Amethyst' },
        { socketType: 'Garnet', name: 'Flawless Masterful Garnet' },
        { socketType: 'Peridot', name: 'Flawless Masterful Peridot' },
        { socketType: 'Lapis', name: 'Flawless Masterful Lapis' },
      ],
    },

  ],
};

export default mageGuide;
