// Auto-generated by wowhead-data-scraper on 2026-04-26. Review before committing.
import type { ClassGuide } from './types';

const monkGuide: ClassGuide = {
  className: 'Monk',
  wowClass: 'monk',
  specs: [
    {
      specName: 'Brewmaster',
      patch: '12.0.5',
      season: 'Midnight Season 1',
      lastUpdated: '2026-04-26',
      links: {
        cheatSheet: 'https://www.wowhead.com/guide/classes/monk/brewmaster/cheat-sheet',
        talents: 'https://www.wowhead.com/guide/classes/monk/brewmaster/talent-builds-pve-tank',
        rotation: 'https://www.wowhead.com/guide/classes/monk/brewmaster/rotation-cooldowns-pve-tank',
        statPriority: 'https://www.wowhead.com/guide/classes/monk/brewmaster/stat-priority-pve-tank',
        consumables: 'https://www.wowhead.com/guide/classes/monk/brewmaster/enchants-gems-pve-tank',
        bisGear: 'https://www.wowhead.com/guide/classes/monk/brewmaster/bis-gear',
        overview: 'https://www.wowhead.com/guide/classes/monk/brewmaster/overview-pve-tank',
      },
      talentLoadouts: [
        { label: 'Raid', exportString: 'CwQAAAAAAAAAAAAAAAAAAAAAAAAAAgZbzYGPwYWM2mxMDAAAAAAALLYEmBmhxmZMmZmZMzywMmZZYZzy2sMMLAAwysMtMbzsMAAQAmhNwMDYaMAAgB' },
        { label: 'Mythic+', exportString: 'CwQAAAAAAAAAAAAAAAAAAAAAAAAAAwMLbGDzwyM2MmZAAAAAAAYZBmYmBmhBzgZmZGzsNMjZWGW2ssNbzYWAAgNEAAgZbWamZmNG2AYmhpxAGAwA' },
        { label: 'Open World', exportString: 'CwQAAAAAAAAAAAAAAAAAAAAAAAAAAgZZzYGzwyM2MmZMAAAAAAALLgYmBmhBzgZmZGzsNMjZWGW2ssNbzYWAAglZZaZ2mZZAAgAYYDMzAmGDYAAD' },
      ],
      statPriority: [
        { stat: 'Agility' },
        { stat: 'Critical Strike' },
        { stat: 'Versatility' },
        { stat: 'Mastery' },
        { stat: 'Haste' },
      ],
      consumables: [
        { type: 'flask', name: 'Flask of the Shattered Sun' },
        { type: 'potion', name: "Light's Potential" },
        { type: 'healthPotion', name: 'Silvermoon Health Potion Healthstone' },
        { type: 'weaponBuff', name: 'Thalassian Phoenix Oil' },
        { type: 'augmentRune', name: 'Void-Touched Augment Rune' },
        { type: 'food', subType: 'feast', name: '(Hearty) Silvermoon Parade/ Harandar Celebration' },
        { type: 'food', subType: 'personal', name: "There are two food items that provide the same effect of increasing your Agility: Royal Roast or Impossibly Royal Roast. Find whichever is cheapest to acquire, or consider an alternative such as Champion's Bento which increases your highest secondary stat instead." },
      ],
      enchants: [
        { slot: 'Helm', name: 'Enchant Helm - Empowered Hex of Leeching Enchant Helm - Empowered Blessing of Speed' },
        { slot: 'Shoulders', name: "Enchant Shoulders - Silvermoon's Mending Enchant Shoulders - Akil'zon's Swiftness" },
        { slot: 'Chest', name: 'Enchant Chest - Mark of the Worldsoul' },
        { slot: 'Legs', name: "Forest Hunter's Armor Kit" },
        { slot: 'Boots', name: "Enchant Boots - Shaladrassil's Roots Enchant Boots - Farstrider's Hunt" },
        { slot: 'Ring', name: "Enchant Ring - Nature's Fury Enchant Ring - Silvermoon's Tenacity", note: 'both rings' },
      ],
      gems: [
        { socketType: 'Peridot:', name: 'Flawless Versatile Peridot' },
        { socketType: 'Amethyst:', name: 'Flawless Deadly Amethyst' },
        { socketType: 'Garnet:', name: 'Flawless Versatile Garnet' },
        { socketType: 'Lapis:', name: 'Flawless Deadly Lapis' },
      ],
    },

    {
      specName: 'Mistweaver',
      patch: '12.0.5',
      season: 'Midnight Season 1',
      lastUpdated: '2026-04-26',
      links: {
        cheatSheet: 'https://www.wowhead.com/guide/classes/monk/mistweaver/cheat-sheet',
        talents: 'https://www.wowhead.com/guide/classes/monk/mistweaver/talent-builds-pve-healer',
        rotation: 'https://www.wowhead.com/guide/classes/monk/mistweaver/rotation-cooldowns-pve-healer',
        statPriority: 'https://www.wowhead.com/guide/classes/monk/mistweaver/stat-priority-pve-healer',
        consumables: 'https://www.wowhead.com/guide/classes/monk/mistweaver/enchants-gems-pve-healer',
        bisGear: 'https://www.wowhead.com/guide/classes/monk/mistweaver/bis-gear',
        overview: 'https://www.wowhead.com/guide/classes/monk/mistweaver/overview-pve-healer',
      },
      talentLoadouts: [
        { label: 'Raid', exportString: 'C4QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAghx2MwmFzYmZZGbYmZYmlttZGLMjmxMgBDGzyMzMDz2gBLmAAAAAIALWmZZ2mZAAgBMAzAGDjFZMDA' },
        { label: 'Mythic+', exportString: 'C4QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMWmZZML2mxMjNjtllZMzmZ2WWmZswMaGzAGMYMLzMzMMbYGsMTAAAAAEgFbzsMLzMAAwAAMDYMwiMmBA' },
        { label: 'Open World', exportString: 'C4QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMWmZZML2mxMjNDYMzmZ222mZswQzYGLYwAGzMzMMbDzwsMTAAAAAEgFbzsNbzMAAAwAMDYMMDZMDA' },
      ],
      statPriority: [
        { stat: 'Intellect' },
        { stat: 'Haste' },
        { stat: 'Critical Strike' },
        { stat: 'Versatility' },
        { stat: 'Mastery' },
      ],
      consumables: [
        { type: 'flask', name: 'Flask of the Blood Knights' },
        { type: 'healthPotion', name: 'Silvermoon Health Potion' },
        { type: 'food', subType: 'feast', name: 'Hearty Harandar Celebration' },
        { type: 'food', subType: 'personal', name: 'Hearty Royal Roast (or the Vegetarian option, Hearty Impossibly Royal Roast)' },
      ],
      enchants: [
        { slot: 'Weapon', name: "Enchant Weapon - Acuity of the Ren'dorei" },
        { slot: 'Chest', name: 'Enchant Chest - Mark of the Worldsoul' },
        { slot: 'Legs', name: 'Sunfire Silk Spellthread' },
        { slot: 'Boots', name: "Enchant Boots - Shaladrassil's Roots" },
        { slot: 'Ring', name: "Enchant Ring - Silvermoon's Alacrity", note: 'both rings' },
      ],
      gems: [
        { socketType: 'Diamond', name: 'Indecipherable Eversong Diamond' },
        { socketType: 'Peridot', name: 'Flawless Deadly Peridot' },
      ],
    },

    {
      specName: 'Windwalker',
      patch: '12.0.5',
      season: 'Midnight Season 1',
      lastUpdated: '2026-04-26',
      links: {
        cheatSheet: 'https://www.wowhead.com/guide/classes/monk/windwalker/cheat-sheet',
        talents: 'https://www.wowhead.com/guide/classes/monk/windwalker/talent-builds-pve-dps',
        rotation: 'https://www.wowhead.com/guide/classes/monk/windwalker/rotation-cooldowns-pve-dps',
        statPriority: 'https://www.wowhead.com/guide/classes/monk/windwalker/stat-priority-pve-dps',
        consumables: 'https://www.wowhead.com/guide/classes/monk/windwalker/enchants-gems-pve-dps',
        bisGear: 'https://www.wowhead.com/guide/classes/monk/windwalker/bis-gear',
        overview: 'https://www.wowhead.com/guide/classes/monk/windwalker/overview-pve-dps',
      },
      talentLoadouts: [
        { label: 'Raid', exportString: 'C0QAAAAAAAAAAAAAAAAAAAAAAMzYMYMYbmZ2mxAAAAAAAAAAAALDjwMMMgZMMzMzwsMMDzyMBAsYmtxwYmZAAsBAzys0MzMLADDMzAwYZMEDYA' },
        { label: 'Mythic+', exportString: 'C0QAAAAAAAAAAAAAAAAAAAAAAMzYMYMYbmZ2mxAAAAAAAAAAAALDzEmhhBMjhZmZGmthZYWmJAgFzsNGGzMDAgNAYWmlmZmZBYYgZGAYZMEDYA' },
        { label: 'Open World', exportString: 'C0QAAAAAAAAAAAAAAAAAAAAAAMzYMYMYbmZ2mxAAAAAAAAAAAALDzEmhhBMjhZmZGmthZYWmJAgFzsNGGzMDAgNAYWmlmZmZBYYgZGAYZMEDYA' },
      ],
      statPriority: [
        { stat: 'Agility' },
        { stat: 'Haste' },
        { stat: 'Critical Strike' },
        { stat: 'Mastery' },
        { stat: 'Versatility' },
      ],
      consumables: [
        { type: 'flask', name: 'Flask of the Blood Knights' },
        { type: 'potion', name: 'Potion of Recklessness' },
        { type: 'healthPotion', name: 'Silvermoon Health Potion' },
        { type: 'weaponBuff', name: 'Thalassian Phoenix Oil' },
        { type: 'augmentRune', name: 'Void-Touched Augment Rune' },
        { type: 'food', subType: 'feast', name: 'Harandar Celebration or Silvermoon Parade.' },
        { type: 'food', subType: 'personal', name: 'Impossibly Royal Roast or Royal Roast.' },
      ],
      enchants: [
        { slot: 'Weapon', name: "Enchant Weapon - Acuity of the Ren'dorei (best to sim for your character)" },
        { slot: 'Helm', name: 'Enchant Helm - Empowered Rune of Avoidance' },
        { slot: 'Shoulders', name: "Enchant Shoulders - Amirdrassil's Grace" },
        { slot: 'Chest', name: 'Enchant Chest - Mark of the Worldsoul' },
        { slot: 'Legs', name: "Forest Hunter's Armor Kit" },
        { slot: 'Boots', name: "Enchant Boots - Lynx's Dexterity" },
        { slot: 'Ring', name: 'Enchant Ring - Eyes of the Eagle', note: 'both rings' },
      ],
      gems: [
        { socketType: 'Peridot', name: 'Flawless Deadly Peridot' },
        { socketType: 'Amethyst', name: 'Flawless Quick Amethyst' },
        { socketType: 'Garnet', name: 'Flawless Quick Garnet' },
      ],
    },

  ],
};

export default monkGuide;
