// Auto-generated by wowhead-data-scraper on 2026-04-26. Review before committing.
import type { ClassGuide, Consumable } from './types';

const SHARED_CONSUMABLES: Consumable[] = [
  { type: 'healthPotion', name: 'Silvermoon Health Potion' },
  { type: 'augmentRune', name: 'Void-Touched Augment Rune' },
];

const paladinGuide: ClassGuide = {
  className: 'Paladin',
  wowClass: 'paladin',
  specs: [
    {
      specName: 'Holy',
      patch: '12.0.5',
      season: 'Midnight Season 1',
      lastUpdated: '2026-04-26',
      links: {
        cheatSheet: 'https://www.wowhead.com/guide/classes/paladin/holy/cheat-sheet',
        talents: 'https://www.wowhead.com/guide/classes/paladin/holy/talent-builds-pve-healer',
        rotation: 'https://www.wowhead.com/guide/classes/paladin/holy/rotation-cooldowns-pve-healer',
        statPriority: 'https://www.wowhead.com/guide/classes/paladin/holy/stat-priority-pve-healer',
        consumables: 'https://www.wowhead.com/guide/classes/paladin/holy/enchants-gems-pve-healer',
        bisGear: 'https://www.wowhead.com/guide/classes/paladin/holy/bis-gear',
        overview: 'https://www.wowhead.com/guide/classes/paladin/holy/overview-pve-healer',
      },
      talentLoadouts: [
        { label: 'Raid', exportString: 'CEEAAAAAAAAAAAAAAAAAAAAAAAAAAYBAMAAglZmZGzYmZ2YMGzyYbmZxoJGzYmZYY2yAwAG2AbsMjZWmtZmZrBAAAYBA2MMmxMAAgZGmxY0A' },
        { label: 'Mythic+', exportString: 'CEEAAAAAAAAAAAAAAAAAAAAAAAAAAYBAMDAwglxMzMzYmZWgxwyYbmZxMNxwYmZYY2yAwAwGYjlZmZWmtZmZrBAAAYhNMDbGYGzAAAmZYGjRD' },
        { label: 'Open World', exportString: 'CEEAAAAAAAAAAAAAAAAAAAAAAAAAAYBAMDAwglxMzMzYmZWgxwyYbmZxoJGGmZYY2yAwAwGYjlZmBABAMzsttYbmhN2YgNDMjZYAYmBgZMGNA' },
      ],
      statPriority: [
        { stat: 'Intellect' },
        { stat: 'Mastery' },
        { stat: 'Critical Strike' },
        { stat: 'Haste' },
        { stat: 'Versatility' },
      ],
      consumables: [
        { type: 'flask', name: 'Flask of the Magisters' },
        { type: 'weaponBuff', name: 'Thalassian Phoenix Oil as Herald Rite of Sanctification as Lightsmith' },
        { type: 'food', subType: 'feast', name: 'Hearty Silvermoon Parade or Hearty Harandar Celebration' },
        { type: 'food', subType: 'personal', name: 'Hearty Royal Roast or Hearty Impossibly Royal Roast' },
        { type: 'food', subType: 'personal', name: 'Sanguithorn Tea. Grants the most mana of any drink and stacks to 1000.' },
        ...SHARED_CONSUMABLES,
      ],
      enchants: [
        { slot: 'Weapon', name: "Enchant Weapon - Acuity of the Ren'dorei" },
        { slot: 'Shoulders', name: "Enchant Shoulders - Silvermoon's Mending" },
        { slot: 'Chest', name: 'Enchant Chest - Mark of the Magister' },
        { slot: 'Legs', name: 'Arcanoweave Spellthread' },
        { slot: 'Boots', name: "Enchant Boots - Shaladrassil's Roots" },
        { slot: 'Ring', name: "Enchant Ring - Zul'jin's Mastery", note: 'both rings' },
      ],
      gems: [
        { socketType: 'Amethyst', name: 'Flawless Quick Amethyst' },
        { socketType: 'Garnet', name: 'Flawless Masterful Garnet' },
        { socketType: 'Peridot', name: 'Flawless Masterful Peridot' },
        { socketType: 'Lapis', name: 'Flawless Masterful Lapis' },
      ],
    },

    {
      specName: 'Protection',
      patch: '12.0.5',
      season: 'Midnight Season 1',
      lastUpdated: '2026-04-26',
      links: {
        cheatSheet: 'https://www.wowhead.com/guide/classes/paladin/protection/cheat-sheet',
        talents: 'https://www.wowhead.com/guide/classes/paladin/protection/talent-builds-pve-tank',
        rotation: 'https://www.wowhead.com/guide/classes/paladin/protection/rotation-cooldowns-pve-tank',
        statPriority: 'https://www.wowhead.com/guide/classes/paladin/protection/stat-priority-pve-tank',
        consumables: 'https://www.wowhead.com/guide/classes/paladin/protection/enchants-gems-pve-tank',
        bisGear: 'https://www.wowhead.com/guide/classes/paladin/protection/bis-gear',
        overview: 'https://www.wowhead.com/guide/classes/paladin/protection/overview-pve-tank',
      },
      talentLoadouts: [
        { label: 'Raid', exportString: 'CIEAAAAAAAAAAAAAAAAAAAAAAsZm5BYWGLzMjZGbLjxYmFbzYAAGAAAAAAkmZWMjZmxYmt2AwAGwgNAAwMTbzMLzAAsBmxAYMDjBAYZGgZGkB' },
        { label: 'Mythic+', exportString: 'CIEAAAAAAAAAAAAAAAAAAAAAAsNjBzyYZMjZmZZbMzwsMLzYAAGAAAAAA00MDzYmhhZrNAMwAmBbAAAEgZmltlWmZsYGMAYMDjBAzMAMzMID' },
        { label: 'Open World', exportString: 'CIEAAAAAAAAAAAAAAAAAAAAAAsNjBzyYZMjZmZZbMzwsMLzYAAGAAAAAA00MziZMzwws1GAGYAzgNAAwMTbzMLzAAsZGMAYMDjBAYZGgZGkB' },
      ],
      statPriority: [
        { stat: 'Strength' },
        { stat: 'Haste' },
        { stat: 'Versatility' },
        { stat: 'Critical Strike' },
        { stat: 'Mastery' },
      ],
      consumables: [
        { type: 'flask', name: 'Flask of the Blood Knights' },
        { type: 'potion', name: "Draught of Rampant Abandon or Light's Potential" },
        { type: 'weaponBuff', name: 'Thalassian Phoenix Oil' },
        ...SHARED_CONSUMABLES,
      ],
      enchants: [
        { slot: 'Weapon', name: "Enchant Weapon - Berserker's Rage" },
        { slot: 'Chest', name: 'Enchant Chest - Mark of the Worldsoul' },
        { slot: 'Head', name: 'Enchant Helm - Empowered Blessing of Speed' },
        { slot: 'Legs', name: "Forest Hunter's Armor Kit" },
        { slot: 'Boots', name: "Enchant Boots - Farstrider's Hunt" },
        { slot: 'Ring', name: "Enchant Ring - Silvermoon's Alacrity", note: 'both rings' },
      ],
      gems: [
        { socketType: 'Peridot', name: 'Flawless Versatile Peridot' },
      ],
    },

    {
      specName: 'Retribution',
      patch: '12.0.5',
      season: 'Midnight Season 1',
      lastUpdated: '2026-04-26',
      links: {
        cheatSheet: 'https://www.wowhead.com/guide/classes/paladin/retribution/cheat-sheet',
        talents: 'https://www.wowhead.com/guide/classes/paladin/retribution/talent-builds-pve-dps',
        rotation: 'https://www.wowhead.com/guide/classes/paladin/retribution/rotation-cooldowns-pve-dps',
        statPriority: 'https://www.wowhead.com/guide/classes/paladin/retribution/stat-priority-pve-dps',
        consumables: 'https://www.wowhead.com/guide/classes/paladin/retribution/enchants-gems-pve-dps',
        bisGear: 'https://www.wowhead.com/guide/classes/paladin/retribution/bis-gear',
        overview: 'https://www.wowhead.com/guide/classes/paladin/retribution/overview-pve-dps',
      },
      talentLoadouts: [
        { label: 'Raid', exportString: 'CYEAAAAAAAAAAAAAAAAAAAAAAAAAAAAQz22MzsMMzAAAAAAwoMmhZGbDz2wMbzYMmZYGbsNMAAkZm2mZ2mBAsBYAwYGmBzYMbYZGMMmxgB' },
        { label: 'Mythic+', exportString: 'CYEAAAAAAAAAAAAAAAAAAAAAAAAAAAAMa22mZmlxMzMDAAAAAwMlhhZGbDz2wMbzYMGDzYjNMAAkZm2mZ2mBAsBYAwYGGYmZYDLzghxMGM' },
        { label: 'Open World', exportString: 'CYEAAAAAAAAAAAAAAAAAAAAAAAAAAAAQzyyMzsMzMzMDAAAAAwMlxMYGbzY2GmZbGMegZwYjtBAAkZm2mZ2mBAsBYAAzwMYYmZBLzgxMmxgB' },
      ],
      statPriority: [
        { stat: 'Strength' },
        { stat: 'Mastery' },
        { stat: 'Critical Strike' },
        { stat: 'Haste' },
        { stat: 'Versatility' },
      ],
      consumables: [
        { type: 'flask', name: 'Flask of the Magisters' },
        { type: 'potion', name: "Light's Potential" },
        { type: 'weaponBuff', name: 'Thalassian Phoenix Oil' },
        ...SHARED_CONSUMABLES,
      ],
      enchants: [
        { slot: 'Weapon', name: "Enchant Weapon - Acuity of the Ren'dorei" },
        { slot: 'Head', name: 'Enchant Helm - Empowered Blessing of Speed' },
        { slot: 'Shoulders', name: "Enchant Shoulders - Akil'zon's Swiftness" },
        { slot: 'Chest', name: 'Enchant Chest - Mark of the Worldsoul' },
        { slot: 'Legs', name: "Forest Hunter's Armor Kit" },
        { slot: 'Boots', name: "Enchant Boots - Farstrider's Hunt" },
        { slot: 'Ring', name: 'Enchant Ring - Eyes of the Eagle', note: 'both rings' },
      ],
      gems: [
        { socketType: 'Diamond', name: 'Indecipherable Eversong Diamond' },
        { socketType: 'Amethyst', name: 'Flawless Deadly Amethyst' },
        { socketType: 'Band', name: "Loa Worshiper's Band" },
        { socketType: 'Garnet', name: 'Flawless Masterful Garnet' },
      ],
    },

  ],
};

export default paladinGuide;
