// Auto-generated by wowhead-data-scraper on 2026-04-26. Review before committing.
import type { ClassGuide, Consumable } from './types';

const SHARED_CONSUMABLES: Consumable[] = [
  { type: 'healthPotion', name: 'Silvermoon Health Potion' },
  { type: 'weaponBuff', name: 'Thalassian Phoenix Oil' },
  { type: 'augmentRune', name: 'Void-Touched Augment Rune' },
];

const priestGuide: ClassGuide = {
  className: 'Priest',
  wowClass: 'priest',
  specs: [
    {
      specName: 'Discipline',
      patch: '12.0.5',
      season: 'Midnight Season 1',
      lastUpdated: '2026-04-26',
      links: {
        cheatSheet: 'https://www.wowhead.com/guide/classes/priest/discipline/cheat-sheet',
        talents: 'https://www.wowhead.com/guide/classes/priest/discipline/talent-builds-pve-healer',
        rotation: 'https://www.wowhead.com/guide/classes/priest/discipline/rotation-cooldowns-pve-healer',
        statPriority: 'https://www.wowhead.com/guide/classes/priest/discipline/stat-priority-pve-healer',
        consumables: 'https://www.wowhead.com/guide/classes/priest/discipline/enchants-gems-pve-healer',
        bisGear: 'https://www.wowhead.com/guide/classes/priest/discipline/bis-gear',
        overview: 'https://www.wowhead.com/guide/classes/priest/discipline/overview-pve-healer',
      },
      talentLoadouts: [
        { label: 'Raid', exportString: 'CAQAAAAAAAAAAAAAAAAAAAAAAADsAz2MzMYmhZbmtZmZmhZAAAAAAAAAAMDLzgZmZwMmBMNTzMAzshhwYWGgxgFAAYMmZMYGgZmZaGG' },
        { label: 'Mythic+', exportString: 'CAQAAAAAAAAAAAAAAAAAAAAAAADsYwyMjZmZGMbzYmZmZMzAAAAAAAAAAYMWmBzMzYzYmBbmmJGgZ2wQYMLDwYwCAAMmZmxgZAmZGBD' },
        { label: 'Open World', exportString: 'CAQAAAAAAAAAAAAAAAAAAAAAAADsYMzGjxYmZMbsNzMzMzAAAAAAAAAAgxYZGMzMjNjZGsZamGwMDACgZZWWAjNDAAjZmZMYGMzAaGG' },
      ],
      statPriority: [
        { stat: 'Intellect' },
        { stat: 'Haste' },
        { stat: 'Critical Strike' },
        { stat: 'Mastery' },
        { stat: 'Versatility' },
      ],
      consumables: [
        { type: 'flask', name: 'Flask of the Blood Knights' },
        { type: 'potion', name: "Lightfused Mana Potion / Light's Potential" },
        { type: 'food', subType: 'feast', name: 'Harandar Celebration' },
        { type: 'food', subType: 'personal', name: 'Royal Roast' },
        ...SHARED_CONSUMABLES,
      ],
      enchants: [
        { slot: 'Weapon', name: "Enchant Weapon - Berserker's Rage" },
        { slot: 'Shoulders', name: "Enchant Shoulders - Silvermoon's Mending" },
        { slot: 'Chest', name: 'Enchant Chest - Mark of the Worldsoul' },
        { slot: 'Helm', name: 'Enchant Helm - Empowered Hex of Leeching' },
        { slot: 'Legs', name: 'Sunfire Silk Spellthread' },
        { slot: 'Boots', name: "Enchant Boots - Shaladrassil's Roots" },
        { slot: 'Ring', name: "Enchant Ring - Silvermoon's Alacrity", note: 'both rings' },
      ],
      gems: [],
    },

    {
      specName: 'Holy',
      patch: '12.0.5',
      season: 'Midnight Season 1',
      lastUpdated: '2026-04-26',
      links: {
        cheatSheet: 'https://www.wowhead.com/guide/classes/priest/holy/cheat-sheet',
        talents: 'https://www.wowhead.com/guide/classes/priest/holy/talent-builds-pve-healer',
        rotation: 'https://www.wowhead.com/guide/classes/priest/holy/rotation-cooldowns-pve-healer',
        statPriority: 'https://www.wowhead.com/guide/classes/priest/holy/stat-priority-pve-healer',
        consumables: 'https://www.wowhead.com/guide/classes/priest/holy/enchants-gems-pve-healer',
        bisGear: 'https://www.wowhead.com/guide/classes/priest/holy/bis-gear',
        overview: 'https://www.wowhead.com/guide/classes/priest/holy/overview-pve-healer',
      },
      talentLoadouts: [
        { label: 'Raid', exportString: 'CEQAAAAAAAAAAAAAAAAAAAAAAwYAAAAAAAgZmlxYMzMDzMzYZGmBAAAwwsMDzMzMYGzAYmaAgZWMTmFDAMGsZmZWA0MMjxwMz2yAMDMA' },
        { label: 'Mythic+', exportString: 'CEQAAAAAAAAAAAAAAAAAAAAAAwYAAAAAAgZzwYWGMmZmZMzMjlZmZAAAAYMWmBzMzYzYmxAmpAAzsZmMbGAYMYzYsAoZMzYMMzstMADYA' },
        { label: 'Open World', exportString: 'CEQAAAAAAAAAAAAAAAAAAAAAAwYAAAAAAAGjZmlZmZMzYYmxYZmxMAAAAGmlZGzMzMMzYGAzUDgZWwQYMbDwYgFGzCgMMPgxwMDwMzMwA' },
      ],
      statPriority: [
        { stat: 'Intellect' },
        { stat: 'Critical Strike' },
        { stat: 'Versatility' },
        { stat: 'Mastery' },
        { stat: 'Haste' },
      ],
      consumables: [
        { type: 'flask', name: 'Flask of the Shattered Sun' },
        { type: 'potion', name: "Lightfused Mana Potion / Light's Potential" },
        { type: 'food', subType: 'feast', name: 'Harandar Celebration' },
        { type: 'food', subType: 'personal', name: 'Royal Roast' },
        ...SHARED_CONSUMABLES,
      ],
      enchants: [
        { slot: 'Weapon', name: "Enchant Weapon - Acuity of the Ren'dorei" },
        { slot: 'Shoulders', name: "Enchant Shoulders - Silvermoon's Mending" },
        { slot: 'Chest', name: 'Enchant Chest - Mark of the Worldsoul' },
        { slot: 'Helm', name: 'Enchant Helm - Empowered Hex of Leeching' },
        { slot: 'Legs', name: 'Sunfire Silk Spellthread' },
        { slot: 'Boots', name: "Enchant Boots - Shaladrassil's Roots" },
        { slot: 'Ring', name: "Enchant Ring - Nature's Fury", note: 'both rings' },
      ],
      gems: [],
    },

    {
      specName: 'Shadow',
      patch: '12.0.5',
      season: 'Midnight Season 1',
      lastUpdated: '2026-04-26',
      links: {
        cheatSheet: 'https://www.wowhead.com/guide/classes/priest/shadow/cheat-sheet',
        talents: 'https://www.wowhead.com/guide/classes/priest/shadow/talent-builds-pve-dps',
        rotation: 'https://www.wowhead.com/guide/classes/priest/shadow/rotation-cooldowns-pve-dps',
        statPriority: 'https://www.wowhead.com/guide/classes/priest/shadow/stat-priority-pve-dps',
        consumables: 'https://www.wowhead.com/guide/classes/priest/shadow/enchants-gems-pve-dps',
        bisGear: 'https://www.wowhead.com/guide/classes/priest/shadow/bis-gear',
        overview: 'https://www.wowhead.com/guide/classes/priest/shadow/overview-pve-dps',
      },
      talentLoadouts: [
        { label: 'Raid', exportString: 'CIQAAAAAAAAAAAAAAAAAAAAAAMMjZGAAAAAAAAAAAgxMMjxyMDzsNzwMsNzMmZmxGyMWMTDwMAzsZGmNDAZMWAwMQGzMzY2GzstMAzED' },
        { label: 'Mythic+', exportString: 'CIQAAAAAAAAAAAAAAAAAAAAAAMMjZGAAAAAAAAAAAghZxMGLzMmZWmZYmx2MGzMzYDZGLmpBYGgZ2MDzmBgMGLAYGIjZmZMbjZ2WGgZiB' },
        { label: 'Open World', exportString: 'CIQAAAAAAAAAAAAAAAAAAAAAAMMjZGAAAAAAAAAAAghZxMGLzMmZWmZYmx2MGzMzYDZGLmpBYGgZ2MDzmBgMGLAYGIjZmZMbjZ2WGgZiB' },
      ],
      statPriority: [
        { stat: 'Intellect' },
        { stat: 'Haste' },
        { stat: 'Mastery' },
        { stat: 'Critical Strike' },
        { stat: 'Versatility' },
      ],
      consumables: [
        { type: 'flask', name: 'Flask of the Blood Knights' },
        { type: 'potion', name: "Light's Potential" },
        { type: 'food', subType: 'feast', name: 'Blooming Feast' },
        { type: 'food', subType: 'personal', name: 'Royal Roast' },
        ...SHARED_CONSUMABLES,
      ],
      enchants: [
        { slot: 'Weapon', name: 'Enchant Weapon - Arcane Mastery' },
        { slot: 'Helm', name: 'Enchant Helm - Empowered Rune of Avoidance' },
        { slot: 'Chest', name: 'Enchant Chest - Mark of the Worldsoul' },
        { slot: 'Shoulders', name: "Enchant Shoulders - Akil'zon's Swiftness" },
        { slot: 'Legs', name: 'Sunfire Silk Spellthread' },
        { slot: 'Boots', name: "Enchant Boots - Lynx's Dexterity" },
        { slot: 'Ring', name: 'Enchant Ring - Eyes of the Eagle', note: 'both rings' },
      ],
      gems: [
        { socketType: 'Peridot', name: 'Flawless Masterful Peridot' },
        { socketType: 'Amethyst', name: 'Flawless Deadly Amethyst' },
        { socketType: 'Garnet', name: 'Flawless Quick Garnet' },
        { socketType: 'Diamond', name: 'Indecipherable Eversong Diamond' },
      ],
    },

  ],
};

export default priestGuide;
