// Auto-generated by wowhead-data-scraper on 2026-04-26. Review before committing.
import type { ClassGuide, Consumable } from './types';

const SHARED_CONSUMABLES: Consumable[] = [
  { type: 'potion', name: "Light's Potential" },
  { type: 'healthPotion', name: 'Silvermoon Health Potion' },
  { type: 'augmentRune', name: 'Void-Touched Augment Rune' },
];

const rogueGuide: ClassGuide = {
  className: 'Rogue',
  wowClass: 'rogue',
  specs: [
    {
      specName: 'Assassination',
      patch: '12.0.5',
      season: 'Midnight Season 1',
      lastUpdated: '2026-04-26',
      links: {
        cheatSheet: 'https://www.wowhead.com/guide/classes/rogue/assassination/cheat-sheet',
        talents: 'https://www.wowhead.com/guide/classes/rogue/assassination/talent-builds-pve-dps',
        rotation: 'https://www.wowhead.com/guide/classes/rogue/assassination/rotation-cooldowns-pve-dps',
        statPriority: 'https://www.wowhead.com/guide/classes/rogue/assassination/stat-priority-pve-dps',
        consumables: 'https://www.wowhead.com/guide/classes/rogue/assassination/enchants-gems-pve-dps',
        bisGear: 'https://www.wowhead.com/guide/classes/rogue/assassination/bis-gear',
        overview: 'https://www.wowhead.com/guide/classes/rogue/assassination/overview-pve-dps',
      },
      talentLoadouts: [
        { label: 'Raid', exportString: 'CMQAAAAAAAAAAAAAAAAAAAAAAYmlxsZwAAAAAAzyglZAAAAAAttNzMzMzMGzMzMbzsMzMDzMzMzMMDzMAGYBmxoxsAy2A2MAYmBGA' },
        { label: 'Mythic+', exportString: 'CMQAAAAAAAAAAAAAAAAAAAAAAYmlxsNDGAAAAAYWGsMDAAAAAottZmZmZmxYmZmZbmlZmZwYmZmxMjhBwALwMGNmFQ2GwmBAzMDGA' },
        { label: 'Open World', exportString: 'CMQAAAAAAAAAAAAAAAAAAAAAAYmlZmNDGAAAAAYWGsNDAAAAAottZmZmZmxYmZmZbmlZG8AzMzMjhZGjBwALwMGNmNQ2GwmxGgZGGD' },
      ],
      statPriority: [
        { stat: 'Agility' },
        { stat: 'Critical Strike' },
        { stat: 'Haste' },
        { stat: 'Mastery' },
        { stat: 'Versatility' },
      ],
      consumables: [
        { type: 'flask', name: 'Flask of the Shattered Sun' },
        { type: 'weaponBuff', name: 'Thalassian Phoenix Oil' },
        ...SHARED_CONSUMABLES,
      ],
      enchants: [
        { slot: 'Helm', name: 'Enchant Helm - Empowered Hex of Leeching' },
        { slot: 'Chest', name: 'Enchant Chest - Mark of the Worldsoul' },
        { slot: 'Legs', name: "Forest Hunter's Armor Kit" },
        { slot: 'Boots', name: "Enchant Boots - Shaladrassil's Roots" },
        { slot: 'Ring', name: "Enchant Ring - Silvermoon's Alacrity", note: 'both rings' },
      ],
      gems: [
        { socketType: 'Diamond', name: 'Indecipherable Eversong Diamond' },
        { socketType: 'Garnet', name: 'Flawless Quick Garnet' },
        { socketType: 'Garnet', name: 'Flawless Quick Garnet' },
      ],
    },

    {
      specName: 'Outlaw',
      patch: '12.0.5',
      season: 'Midnight Season 1',
      lastUpdated: '2026-04-26',
      links: {
        cheatSheet: 'https://www.wowhead.com/guide/classes/rogue/outlaw/cheat-sheet',
        talents: 'https://www.wowhead.com/guide/classes/rogue/outlaw/talent-builds-pve-dps',
        rotation: 'https://www.wowhead.com/guide/classes/rogue/outlaw/rotation-cooldowns-pve-dps',
        statPriority: 'https://www.wowhead.com/guide/classes/rogue/outlaw/stat-priority-pve-dps',
        consumables: 'https://www.wowhead.com/guide/classes/rogue/outlaw/enchants-gems-pve-dps',
        bisGear: 'https://www.wowhead.com/guide/classes/rogue/outlaw/bis-gear',
        overview: 'https://www.wowhead.com/guide/classes/rogue/outlaw/overview-pve-dps',
      },
      talentLoadouts: [
        { label: 'Raid', exportString: 'CQQAAAAAAAAAAAAAAAAAAAAAAAgx2MYmZmZmtZmZmZMmNeAmZbaZw2MAAAAAgZbbmZGmZmZGzMz2AAAAwYAwYWMMkBmFWoF2YAmZwAD' },
        { label: 'Mythic+', exportString: 'CQQAAAAAAAAAAAAAAAAAAAAAAAgx2MYmZMzsNzMzMzMzsBmZbaZw2MAAAAAgZbbmZGmZmZGzMz2AAAAwYAwYWMMkBmFWoF2YAmZwAD' },
        { label: 'Open World', exportString: 'CQQAAAAAAAAAAAAAAAAAAAAAAAgx2MYmZMzsNzMzMzMzsBmZbaZw2MAAAAAA2mZmhZmZmxMzsMAAAAMGAMmFDDZgZhFahNGgZGMDmB' },
      ],
      statPriority: [
        { stat: 'Agility' },
        { stat: 'Haste' },
        { stat: 'Critical Strike' },
        { stat: 'Versatility' },
        { stat: 'Mastery' },
      ],
      consumables: [
        { type: 'flask', name: 'Flask of the Shattered Sun or Flask of the Blood Knights' },
        { type: 'weaponBuff', name: 'Thalassian Phoenix Oil' },
        { type: 'food', subType: 'feast', name: 'Harandar Celebration' },
        { type: 'food', subType: 'personal', name: 'Hearty Royal Roast' },
        ...SHARED_CONSUMABLES,
      ],
      enchants: [
        { slot: 'Weapon', name: "Enchant Weapon - Jan'alai's Precision or Enchant Weapon - Acuity of the Ren'dorei" },
        { slot: 'Chest', name: 'Enchant Chest - Mark of the Worldsoul' },
        { slot: 'Legs', name: "Forest Hunter's Armor Kit" },
        { slot: 'Boots', name: "Enchant Boots - Shaladrassil's Roots" },
        { slot: 'Ring', name: "Enchant Ring - Eyes of the Eagle or Enchant Ring - Silvermoon's Alacrity", note: 'both rings' },
      ],
      gems: [
        { socketType: 'Peridot', name: 'Flawless Deadly Peridot' },
        { socketType: 'Onyx', name: 'Flawless Deadly Amethyst' },
        { socketType: 'Garnet', name: 'Flawless Quick Garnet' },
        { socketType: 'Lapis', name: 'Flawless Quick Lapis' },
      ],
    },

    {
      specName: 'Subtlety',
      patch: '12.0.5',
      season: 'Midnight Season 1',
      lastUpdated: '2026-04-26',
      links: {
        cheatSheet: 'https://www.wowhead.com/guide/classes/rogue/subtlety/cheat-sheet',
        talents: 'https://www.wowhead.com/guide/classes/rogue/subtlety/talent-builds-pve-dps',
        rotation: 'https://www.wowhead.com/guide/classes/rogue/subtlety/rotation-cooldowns-pve-dps',
        statPriority: 'https://www.wowhead.com/guide/classes/rogue/subtlety/stat-priority-pve-dps',
        consumables: 'https://www.wowhead.com/guide/classes/rogue/subtlety/enchants-gems-pve-dps',
        bisGear: 'https://www.wowhead.com/guide/classes/rogue/subtlety/bis-gear',
        overview: 'https://www.wowhead.com/guide/classes/rogue/subtlety/overview-pve-dps',
      },
      talentLoadouts: [
        { label: 'Raid', exportString: 'CUQAAAAAAAAAAAAAAAAAAAAAAAgx2MAAAAAwsMGLTYbZmxMjZgZmZmtxsNmZstNzMzMzMGMmZbAAAAYwYAjZxwADMLahWshZAzMYGDA' },
        { label: 'Mythic+', exportString: 'CUQAAAAAAAAAAAAAAAAAAAAAAAgx2MAAAAAwsMGLTYbZMmZMjxDMzMzsNmthZstNzMzMzMGMmZbAAAAYwYAjZxwADMLahWshZAzMYGDA' },
        { label: 'Open World', exportString: 'CUQAAAAAAAAAAAAAAAAAAAAAAAgx2MAAAAAwsMGLTMbLjxMjZMMzMzYMbzYGbbzMzMzMjBjZ2GAAAAGMGwYWMMwAziWoFbYGwMDmxA' },
      ],
      statPriority: [
        { stat: 'Agility' },
        { stat: 'Critical Strike' },
        { stat: 'Haste' },
        { stat: 'Mastery' },
        { stat: 'Versatility' },
      ],
      consumables: [
        { type: 'flask', name: 'Flask of the Shattered Sun (best) Flask of the Magisters (alternative)' },
        { type: 'food', subType: 'feast', name: 'Silvermoon Parade' },
        { type: 'food', subType: 'personal', name: 'Royal Roast' },
        ...SHARED_CONSUMABLES,
      ],
      enchants: [
        { slot: 'Head', name: 'Enchant Helm - Empowered Rune of Avoidance' },
        { slot: 'Shoulders', name: "Enchant Shoulders - Amirdrassil's Grace" },
        { slot: 'Chest', name: 'Enchant Chest - Mark of the Worldsoul' },
        { slot: 'Legs', name: "Forest Hunter's Armor Kit" },
        { slot: 'Boots', name: "Enchant Boots - Lynx's Dexterity" },
        { slot: 'Ring', name: 'Enchant Ring - Eyes of the Eagle', note: 'both rings' },
      ],
      gems: [
        { socketType: 'Amethyst', name: 'Flawless Quick Amethyst' },
        { socketType: 'Peridot', name: 'Flawless Deadly Peridot' },
        { socketType: 'Garnet', name: 'Flawless Masterful Garnet' },
      ],
    },

  ],
};

export default rogueGuide;
