// Auto-generated by wowhead-data-scraper on 2026-04-26. Review before committing.
import type { ClassGuide, Consumable } from './types';

const SHARED_CONSUMABLES: Consumable[] = [
  { type: 'healthPotion', name: 'Silvermoon Health Potion' },
  { type: 'augmentRune', name: 'Void-Touched Augment Rune' },
];

const shamanGuide: ClassGuide = {
  className: 'Shaman',
  wowClass: 'shaman',
  specs: [
    {
      specName: 'Elemental',
      patch: '12.0.5',
      season: 'Midnight Season 1',
      lastUpdated: '2026-04-26',
      links: {
        cheatSheet: 'https://www.wowhead.com/guide/classes/shaman/elemental/cheat-sheet',
        talents: 'https://www.wowhead.com/guide/classes/shaman/elemental/talent-builds-pve-dps',
        rotation: 'https://www.wowhead.com/guide/classes/shaman/elemental/rotation-cooldowns-pve-dps',
        statPriority: 'https://www.wowhead.com/guide/classes/shaman/elemental/stat-priority-pve-dps',
        consumables: 'https://www.wowhead.com/guide/classes/shaman/elemental/enchants-gems-pve-dps',
        bisGear: 'https://www.wowhead.com/guide/classes/shaman/elemental/bis-gear',
        overview: 'https://www.wowhead.com/guide/classes/shaman/elemental/overview-pve-dps',
      },
      talentLoadouts: [
        { label: 'Raid', exportString: 'CYQAAAAAAAAAAAAAAAAAAAAAAAAAAAzMbLzMmZmZZbbgxMDAAAAAsYGDbwCMjGasBAzyMzMGbLmwMzyYZmZmxwysMjFzMjZWAAGAzMwwwA' },
        { label: 'Mythic+', exportString: 'CYQAAAAAAAAAAAAAAAAAAAAAAAAAAAzMbLzMzYML2mhZMzAAAAAALmxwGsAzohGbAwsMzMjx2ipNmZMWmZmZMsMLGLmZGzsAAMDwMDMMMA' },
        { label: 'Open World', exportString: 'CYQAAAAAAAAAAAAAAAAAAAAAAAAAAAzMLLzMmZmZbZZMmxMDAAAAYzMbwAGwsxEysAAzyMzMGbLmwMjxyMzMzMjFLGLYMzsAAMAwMjhhB' },
      ],
      statPriority: [
        { stat: 'Intellect' },
        { stat: 'Mastery' },
        { stat: 'Haste' },
        { stat: 'Critical Strike' },
        { stat: 'Versatility' },
      ],
      consumables: [
        { type: 'flask', name: 'Flask of the Magisters' },
        { type: 'potion', name: "Light's Potential" },
        { type: 'weaponBuff', name: 'Flametongue Weapon/ Thalassian Phoenix Oil' },
        ...SHARED_CONSUMABLES,
      ],
      enchants: [
        { slot: 'Weapon', name: 'Enchant Weapon - Arcane Mastery' },
        { slot: 'Head', name: 'Enchant Helm - Empowered Rune of Avoidance' },
        { slot: 'Chest', name: 'Enchant Chest - Mark of the Worldsoul' },
        { slot: 'Legs', name: 'Sunfire Silk Spellthread' },
        { slot: 'Boots', name: "Enchant Boots - Lynx's Dexterity" },
        { slot: 'Ring', name: "Enchant Ring - Zul'jin's Mastery", note: 'both rings' },
      ],
      gems: [
        { socketType: 'Garnet', name: 'Flawless Masterful Garnet' },
        { socketType: 'Peridot', name: 'Flawless Masterful Peridot' },
        { socketType: 'Amethyst', name: 'Flawless Deadly Amethyst' },
        { socketType: 'Lapis', name: 'Flawless Masterful Lapis' },
      ],
    },

    {
      specName: 'Enhancement',
      patch: '12.0.5',
      season: 'Midnight Season 1',
      lastUpdated: '2026-04-26',
      links: {
        cheatSheet: 'https://www.wowhead.com/guide/classes/shaman/enhancement/cheat-sheet',
        talents: 'https://www.wowhead.com/guide/classes/shaman/enhancement/talent-builds-pve-dps',
        rotation: 'https://www.wowhead.com/guide/classes/shaman/enhancement/rotation-cooldowns-pve-dps',
        statPriority: 'https://www.wowhead.com/guide/classes/shaman/enhancement/stat-priority-pve-dps',
        consumables: 'https://www.wowhead.com/guide/classes/shaman/enhancement/enchants-gems-pve-dps',
        bisGear: 'https://www.wowhead.com/guide/classes/shaman/enhancement/bis-gear',
        overview: 'https://www.wowhead.com/guide/classes/shaman/enhancement/overview-pve-dps',
      },
      talentLoadouts: [
        { label: 'Raid', exportString: 'CcQAAAAAAAAAAAAAAAAAAAAAAMzMjZmZmZmZmZmZmZGAAAAAAAAAYB2gZsox2AYmgNAmlZMzMWWmBmZ2YZmZmhhxMAAGgxMTMzAAjB' },
        { label: 'Mythic+', exportString: 'CcQAAAAAAAAAAAAAAAAAAAAAAMzMjZmZmZmZmZmZGzAAAAAAAAAALwGMjFN2GAzEsBwsMjZMWWMwMz2YZmZmZwyYGAAgxYGxMDwgxA' },
        { label: 'Open World', exportString: 'CcQAAAAAAAAAAAAAAAAAAAAAAMzMjZmZmZmZmZmZmZGAAAAAAAAAYB2gZsox2AYmgNAmlZMjxyyMwMjxiZmZGjFmBAAYMmZiZGAYMA' },
      ],
      statPriority: [
        { stat: 'Agility' },
        { stat: 'Mastery' },
        { stat: 'Haste' },
        { stat: 'Critical Strike' },
        { stat: 'Versatility' },
      ],
      consumables: [
        { type: 'flask', name: 'Flask of the Magisters' },
        { type: 'potion', name: "Light's Potential" },
        { type: 'weaponBuff', name: 'Weapon Imbues' },
        { type: 'food', subType: 'feast', name: 'Silvermoon Parade' },
        { type: 'food', subType: 'personal', name: 'Royal Roast' },
        ...SHARED_CONSUMABLES,
      ],
      enchants: [
        { slot: 'Helm', name: 'Enchant Helm - Empowered Rune of Avoidance' },
        { slot: 'Shoulders', name: "Enchant Shoulders - Amirdrassil's Grace" },
        { slot: 'Bracers', name: 'Radiant Jewelbinder' },
        { slot: 'Chest', name: 'Enchant Chest - Mark of the Worldsoul' },
        { slot: 'Belt', name: 'Radiant Jewelbinder' },
        { slot: 'Legs', name: "Forest Hunter's Armor Kit" },
        { slot: 'Boots', name: "Enchant Boots - Lynx's Dexterity" },
        { slot: 'Ring', name: "Enchant Ring - Zul'jin's Mastery", note: 'both rings' },
      ],
      gems: [
        { socketType: 'Eversong Diamond', name: 'Indecipherable Eversong Diamond .' },
        { socketType: 'Other Gems', name: 'Flawless Quick Amethyst  and  Flawless Masterful Peridot' },
      ],
    },

    {
      specName: 'Restoration',
      patch: '12.0.5',
      season: 'Midnight Season 1',
      lastUpdated: '2026-04-26',
      links: {
        cheatSheet: 'https://www.wowhead.com/guide/classes/shaman/restoration/cheat-sheet',
        talents: 'https://www.wowhead.com/guide/classes/shaman/restoration/talent-builds-pve-healer',
        rotation: 'https://www.wowhead.com/guide/classes/shaman/restoration/rotation-cooldowns-pve-healer',
        statPriority: 'https://www.wowhead.com/guide/classes/shaman/restoration/stat-priority-pve-healer',
        consumables: 'https://www.wowhead.com/guide/classes/shaman/restoration/enchants-gems-pve-healer',
        bisGear: 'https://www.wowhead.com/guide/classes/shaman/restoration/bis-gear',
        overview: 'https://www.wowhead.com/guide/classes/shaman/restoration/overview-pve-healer',
      },
      talentLoadouts: [
        { label: 'Raid', exportString: 'CgQAAAAAAAAAAAAAAAAAAAAAAAAAAgBAAAAzMzMLLbDzMGzMmZGzsYmNYATwsxEYsYGmBbjxMNbLzMMjZhFzMzYGmlBAAAmZGAMzADG' },
        { label: 'Mythic+', exportString: 'CgQAAAAAAAAAAAAAAAAAAAAAAAAAAgBAAAAjZmZbZbYmZGzMGzYmFzsADYCmFmAjFmZGMbzMGNbLzMMjZhFjZGzYZWGAAMAzMDAmZgBD' },
        { label: 'Open World', exportString: 'CgQAAAAAAAAAAAAAAAAAAAAAAAAAAgBAAAAjZmxy2MMzMzMzMmxYxMLwAmgZhJwYBzMY2mZmRz2yMDmZwyMmZMjlZBAAGgZmBAzMMGM' },
      ],
      statPriority: [
        { stat: 'Intellect' },
        { stat: 'Critical Strike' },
        { stat: 'Versatility' },
        { stat: 'Mastery' },
        { stat: 'Haste' },
      ],
      consumables: [
        { type: 'flask', name: 'Flask of the Shattered Sun' },
        { type: 'potion', name: 'Lightfused Mana Potion Potion of Recklessness' },
        { type: 'weaponBuff', name: 'Earthliving Weapon' },
        { type: 'food', subType: 'feast', name: 'Silvermoon Parade' },
        { type: 'food', subType: 'personal', name: 'Royal Roast' },
        ...SHARED_CONSUMABLES,
      ],
      enchants: [
        { slot: 'Weapon', name: "Enchant Weapon - Acuity of the Ren'dorei" },
        { slot: 'Helm', name: 'Enchant Helm - Empowered Hex of Leeching' },
        { slot: 'Shoulders', name: "Enchant Shoulders - Silvermoon's Mending" },
        { slot: 'Chest', name: 'Enchant Chest - Mark of the Magister' },
        { slot: 'Legs', name: 'Arcanoweave Spellthread' },
        { slot: 'Boots', name: "Enchant Boots - Shaladrassil's Roots" },
        { slot: 'Ring', name: "Enchant Ring - Nature's Fury", note: 'both rings' },
      ],
      gems: [
        { socketType: 'Garnet', name: 'Flawless Versatile Garnet' },
        { socketType: 'Peridot', name: 'Flawless Deadly Peridot' },
        { socketType: 'Lapis', name: 'Flawless Deadly Lapis' },
        { socketType: 'Amethyst', name: 'Flawless Deadly Amethyst' },
      ],
    },

  ],
};

export default shamanGuide;
