// Auto-generated by wowhead-data-scraper on 2026-04-26. Review before committing.
import type { ClassGuide, Consumable } from './types';

const SHARED_CONSUMABLES: Consumable[] = [
  { type: 'healthPotion', name: 'Silvermoon Health Potion' },
  { type: 'weaponBuff', name: 'Thalassian Phoenix Oil' },
  { type: 'augmentRune', name: 'Void-Touched Augment Rune' },
];

const warriorGuide: ClassGuide = {
  className: 'Warrior',
  wowClass: 'warrior',
  specs: [
    {
      specName: 'Arms',
      patch: '12.0.5',
      season: 'Midnight Season 1',
      lastUpdated: '2026-04-26',
      links: {
        cheatSheet: 'https://www.wowhead.com/guide/classes/warrior/arms/cheat-sheet',
        talents: 'https://www.wowhead.com/guide/classes/warrior/arms/talent-builds-pve-dps',
        rotation: 'https://www.wowhead.com/guide/classes/warrior/arms/rotation-cooldowns-pve-dps',
        statPriority: 'https://www.wowhead.com/guide/classes/warrior/arms/stat-priority-pve-dps',
        consumables: 'https://www.wowhead.com/guide/classes/warrior/arms/enchants-gems-pve-dps',
        bisGear: 'https://www.wowhead.com/guide/classes/warrior/arms/bis-gear',
        overview: 'https://www.wowhead.com/guide/classes/warrior/arms/overview-pve-dps',
      },
      talentLoadouts: [
        { label: 'Raid', exportString: 'CcEAAAAAAAAAAAAAAAAAAAAAAAzMzsMzMzMDAAAghphxYGWmZmZGMmZAAAAAMzyMDIjxyyALgBMDTIzgNwMjNz2YwMGgZGAmxwA' },
        { label: 'Mythic+', exportString: 'CcEAAAAAAAAAAAAAAAAAAAAAAgZmxsMzMzYGAAAghphxwMbLzMzMjZGzMAAAAAGbmB2iBsZGDLwAzoNaMYBYGMGMbmtBzMAgZmhB' },
        { label: 'Open World', exportString: 'CcEAAAAAAAAAAAAAAAAAAAAAAgZmxsMzMzYGAAAghphxwMbLzMzMjZGzMAAAAAGbmB2iBsZGDLwAzoNaMYBYGMGMbmtBzMAgZmhB' },
      ],
      statPriority: [
        { stat: 'Strength' },
        { stat: 'Critical Strike' },
        { stat: 'Haste' },
        { stat: 'Mastery' },
        { stat: 'Versatility' },
      ],
      consumables: [
        { type: 'flask', name: 'Flask of the Shattered Sun' },
        { type: 'potion', name: "Light's Potential" },
        ...SHARED_CONSUMABLES,
      ],
      enchants: [
        { slot: 'Weapon', name: "Enchant Weapon - Acuity of the Ren'dorei" },
        { slot: 'Helm', name: 'Enchant Helm - Empowered Hex of Leeching' },
        { slot: 'Chest', name: 'Enchant Chest - Mark of the Worldsoul' },
        { slot: 'Legs', name: "Blood Knight's Armor Kit" },
        { slot: 'Boots', name: "Enchant Boots - Lynx's Dexterity" },
        { slot: 'Ring', name: "Enchant Ring - Nature's Fury", note: 'both rings' },
      ],
      gems: [
        { socketType: 'Diamond', name: 'Indecipherable Eversong Diamond' },
        { socketType: 'Diamond', name: 'Powerful Eversong Diamond' },
        { socketType: 'Garnet', name: 'Flawless Quick Garnet' },
        { socketType: 'Peridot', name: 'Flawless Deadly Peridot' },
      ],
    },

    {
      specName: 'Fury',
      patch: '12.0.5',
      season: 'Midnight Season 1',
      lastUpdated: '2026-04-26',
      links: {
        cheatSheet: 'https://www.wowhead.com/guide/classes/warrior/fury/cheat-sheet',
        talents: 'https://www.wowhead.com/guide/classes/warrior/fury/talent-builds-pve-dps',
        rotation: 'https://www.wowhead.com/guide/classes/warrior/fury/rotation-cooldowns-pve-dps',
        statPriority: 'https://www.wowhead.com/guide/classes/warrior/fury/stat-priority-pve-dps',
        consumables: 'https://www.wowhead.com/guide/classes/warrior/fury/enchants-gems-pve-dps',
        bisGear: 'https://www.wowhead.com/guide/classes/warrior/fury/bis-gear',
        overview: 'https://www.wowhead.com/guide/classes/warrior/fury/overview-pve-dps',
      },
      talentLoadouts: [
        { label: 'Raid', exportString: 'CgEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgGDjxMsMzMzMDjZmZGzMzsMzMGzMbDzMAAQMWWGYBMBzwEYG2AmZ2Y2GAAMzYYMzMMYA' },
        { label: 'Mythic+', exportString: 'CgEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgGDjZMz2yMzMjZmxMjZMjZWmZGjZmlxMzAAAhB2glFjGzAysgZsAYGMGAMzAYYmZGMYA' },
        { label: 'Open World', exportString: 'CgEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgGDjZMz2yMzMjZmxMjZMjZWmZGjZmlxMzAAAhB2glFjGzAysgZsAYGMGAMzAYYmZGMYA' },
      ],
      statPriority: [
        { stat: 'Strength' },
        { stat: 'Mastery' },
        { stat: 'Haste' },
        { stat: 'Critical Strike' },
        { stat: 'Versatility' },
      ],
      consumables: [
        { type: 'flask', name: 'Flask of the Magisters' },
        { type: 'potion', name: "Light's Potential" },
        ...SHARED_CONSUMABLES,
      ],
      enchants: [
        { slot: 'Weapon', name: 'Enchant Weapon - Arcane Mastery' },
        { slot: 'Helm', name: 'Enchant Helm - Empowered Hex of Leeching' },
        { slot: 'Chest', name: 'Enchant Chest - Mark of the Worldsoul' },
        { slot: 'Legs', name: "Blood Knight's Armor Kit" },
        { slot: 'Boots', name: "Enchant Boots - Lynx's Dexterity" },
        { slot: 'Ring', name: "Enchant Ring - Zul'jin's Mastery", note: 'both rings' },
      ],
      gems: [
        { socketType: 'Diamond', name: 'Indecipherable Eversong Diamond' },
        { socketType: 'Diamond', name: 'Powerful Eversong Diamond' },
        { socketType: 'Amethyst', name: 'Flawless Quick Amethyst' },
        { socketType: 'Peridot', name: 'Flawless Masterful Peridot' },
      ],
    },

    {
      specName: 'Protection',
      patch: '12.0.5',
      season: 'Midnight Season 1',
      lastUpdated: '2026-04-26',
      links: {
        cheatSheet: 'https://www.wowhead.com/guide/classes/warrior/protection/cheat-sheet',
        talents: 'https://www.wowhead.com/guide/classes/warrior/protection/talent-builds-pve-tank',
        rotation: 'https://www.wowhead.com/guide/classes/warrior/protection/rotation-cooldowns-pve-tank',
        statPriority: 'https://www.wowhead.com/guide/classes/warrior/protection/stat-priority-pve-tank',
        consumables: 'https://www.wowhead.com/guide/classes/warrior/protection/enchants-gems-pve-tank',
        bisGear: 'https://www.wowhead.com/guide/classes/warrior/protection/bis-gear',
        overview: 'https://www.wowhead.com/guide/classes/warrior/protection/overview-pve-tank',
      },
      talentLoadouts: [
        { label: 'Raid', exportString: 'CkEAAAAAAAAAAAAAAAAAAAAAA0yAAAzMzYmZGzY2MzsMjxYmGmZYZMzMDzYmBAAAALDAzYAGYDWWMaMDgZLmZDmxMDmtBAzMAAMAD' },
        { label: 'Mythic+', exportString: 'CkEAAAAAAAAAAAAAAAAAAAAAAkBAAGzMzMzMmxsZmZZGjxMNmxwyYmZYmxMDAAAAWGAmxAMwGssY0YGAzWMzGMzMzgZZAwMDAADwA' },
        { label: 'Open World', exportString: 'CkEAAAAAAAAAAAAAAAAAAAAAAkBAAGzYmZmZmxsZmZZGjxMNmxwyYmZGmxMDAAAAWGAmxAAbmxwGZgZYhGzsAzMzMY2GAgZGAwAMA' },
      ],
      statPriority: [
        { stat: 'Strength' },
        { stat: 'Haste' },
        { stat: 'Critical Strike' },
        { stat: 'Versatility' },
        { stat: 'Mastery' },
      ],
      consumables: [
        { type: 'flask', name: 'Flask of the Blood Knights' },
        { type: 'potion', name: "Draught of Rampant Abandon or Light's Potential" },
        ...SHARED_CONSUMABLES,
      ],
      enchants: [
        { slot: 'Weapon', name: "Enchant Weapon - Berserker's Rage" },
        { slot: 'Chest', name: 'Enchant Chest - Mark of the Worldsoul' },
        { slot: 'Head', name: 'Enchant Helm - Empowered Blessing of Speed' },
        { slot: 'Legs', name: "Forest Hunter's Armor Kit" },
        { slot: 'Boots', name: "Enchant Boots - Farstrider's Hunt" },
        { slot: 'Ring', name: "Enchant Ring - Silvermoon's Alacrity", note: 'both rings' },
      ],
      gems: [
        { socketType: 'Peridot', name: 'Flawless Versatile Peridot' },
      ],
    },

  ],
};

export default warriorGuide;
